CREATE TABLE `PALIKA` (
  `P_ID` INT NOT NULL,
  `P_CODE` INT DEFAULT NULL,
  `PROVINCE` VARCHAR(16) DEFAULT NULL,
  `DISTRICT` VARCHAR(18) DEFAULT NULL,
  `LOCAL_GOV_EN` VARCHAR(46) DEFAULT NULL,
  `LOCAL_GOV_NP` VARCHAR(34) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `PALIKA` (`P_ID`, `P_CODE`, `PROVIENCE`, `DISTRICT`, `LOCAL_GOV_EN`, `LOCAL_GOV_NP`) VALUES
(1, 10101, 'Koshi', 'Taplejung', 'Phaktanlung Rural Municipality', 'फक्ताङ्लुङ्ग गाउँपालिका'),
(2, 10102, 'Koshi', 'Taplejung', 'Mikwakhola Rural Municipality', 'मिक्वाखोला गाउँपालिका'),
(3, 10103, 'Koshi', 'Taplejung', 'Meringden Rural Municipality', 'मेरिङ्गदेन गाउँपालिका'),
(4, 10104, 'Koshi', 'Taplejung', 'Maiwakhola Rural Municipality', 'मैवाखोला गाउँपालिका'),
(5, 10105, 'Koshi', 'Taplejung', 'Aatharai Tribeni Rural Municipality', 'आठराई त्रिवेणी गाउँपालिका'),
(6, 10106, 'Koshi', 'Taplejung', 'Phungling Urban Municipality', 'फुङलिङ्ग नगरपालिका'),
(7, 10107, 'Koshi', 'Taplejung', 'Pathivara Yangwarak Rural Municipality', 'पाथीभरा याङवरक गाउँपालिका'),
(8, 10108, 'Koshi', 'Taplejung', 'Sirijanga Rural Municipality', 'सिरीजङ्गा गाउंपालिका'),
(9, 10109, 'Koshi', 'Taplejung', 'Sidingba Rural Municipality', 'सिदिङ्गवा गाउँपालिका'),
(10, 10201, 'Koshi', 'Sankhuwasabha', 'Bhotkhola Rural Municipality', 'भोटखोला गाउँपालिका'),
(11, 10202, 'Koshi', 'Sankhuwasabha', 'Makalu Rural Municipality', 'मकालु गाउँपालिका'),
(12, 10203, 'Koshi', 'Sankhuwasabha', 'Silichong Rural Municipality', 'सिलीचोङ गाउँपालिका'),
(13, 10204, 'Koshi', 'Sankhuwasabha', 'Chichila Rural Municipality', 'चिचिला गाउँपालिका'),
(14, 10205, 'Koshi', 'Sankhuwasabha', 'Sabhapokhari Rural Municipality', 'सभापोखरी गाउँपालिका'),
(15, 10206, 'Koshi', 'Sankhuwasabha', 'Khandabari Urban Municipality', 'खाँदबारी नगरपालिका'),
(16, 10207, 'Koshi', 'Sankhuwasabha', 'Panchakhapan Urban Municipality', 'पाँचखपन नगरपालिका'),
(17, 10208, 'Koshi', 'Sankhuwasabha', 'Chainapur Urban Municipality', 'चैनपुर नगरपालिका'),
(18, 10209, 'Koshi', 'Sankhuwasabha', 'Madi Urban Municipality', 'मादी नगरपालिका'),
(19, 10210, 'Koshi', 'Sankhuwasabha', 'Dharmadevi Urban Municipality', 'धर्मदेवी नगरपालिका'),
(20, 10301, 'Koshi', 'Solukhumbu', 'Khumbu Pasanglhamu Rural Municipality', 'खुम्बु पासाङल्हामु गाउँपालिका'),
(21, 10302, 'Koshi', 'Solukhumbu', 'Mahakulung Rural Municipality', 'माहाकुलुङ गाउँपालिका'),
(22, 10303, 'Koshi', 'Solukhumbu', 'Sotang Rural Municipality', 'सोताङ गाउँपालिका'),
(23, 10304, 'Koshi', 'Solukhumbu', 'Mapya Dudhkoshi Rural Municipality', 'माप्य दुधकोशी गाउँपालिका'),
(24, 10305, 'Koshi', 'Solukhumbu', 'Thulung Dudhkoshi Rural Municipality', 'थुलुङ दुधकोशी गाउँपालिका'),
(25, 10306, 'Koshi', 'Solukhumbu', 'Necha Salyan Rural Municipality', 'नेचासल्यान गाउँपालिका'),
(26, 10307, 'Koshi', 'Solukhumbu', 'Solu Dhudhakunda Urban Municipality', 'सोलुदुधकुण्ड नगरपालिका'),
(27, 10308, 'Koshi', 'Solukhumbu', 'Likhu Pike Rural Municipality', 'लिखु पिके गाउँपालिका'),
(28, 10401, 'Koshi', 'Okhaldhunga', 'Chishankhu Gadhi Rural Municipality', 'चिशंखुगढी गाउँपालिका'),
(29, 10402, 'Koshi', 'Okhaldhunga', 'Siddhicharan Urban Municipality', 'सिद्धिचरण नगरपालिका'),
(30, 10403, 'Koshi', 'Okhaldhunga', 'Molung Rural Municipality', 'मोलुङ्ग गाउँपालिका'),
(31, 10404, 'Koshi', 'Okhaldhunga', 'Khiji Demba Rural Municipality', 'खिजीदेम्बा गाउँपालिका'),
(32, 10405, 'Koshi', 'Okhaldhunga', 'Likhu Rural Municipality', 'लिखु गाउँपालिका'),
(33, 10406, 'Koshi', 'Okhaldhunga', 'Champadevi Rural Municipality', 'चम्पादेवी गाउँपालिका'),
(34, 10407, 'Koshi', 'Okhaldhunga', 'Sunkoshi Rural Municipality', 'सुनकोशी गाउँपालिका'),
(35, 10408, 'Koshi', 'Okhaldhunga', 'Manebhanjyang Rural Municipality', 'मानेभन्ज्याङ्ग गाउँपालिका'),
(36, 10501, 'Koshi', 'Khotang', 'Kepilasgadhi Rural Municipality', 'केपिलासगढी गाउँपालिका'),
(37, 10502, 'Koshi', 'Khotang', 'Aiselukharka Rural Municipality', 'ऐसेलुखर्क गाउँपालिका'),
(38, 10503, 'Koshi', 'Khotang', 'Rawa Besi Rural Municipality', 'रावा बेसी गाउँपालिका'),
(39, 10504, 'Koshi', 'Khotang', 'Halesi Tuwachung Urban Municipality', 'हलेसी तुवाचुङ नगरपालिका'),
(40, 10505, 'Koshi', 'Khotang', 'Diktel Rupakot Majhuwagadhi Urban Municipality', 'दिक्तेल रुपाकोट मझुवागढी नगरपालिका'),
(41, 10506, 'Koshi', 'Khotang', 'Sakela Rural Municipality', 'साकेला गाउँपालिका'),
(42, 10507, 'Koshi', 'Khotang', 'Diprung Chuichumma Rural Municipality', 'दिप्रुङ चुइचुम्मा गाउँपालिका'),
(43, 10508, 'Koshi', 'Khotang', 'Khotehang Rural Municipality', 'खोटेहाङ गाउँपालिका'),
(44, 10509, 'Koshi', 'Khotang', 'Jante Dhunga Rural Municipality', 'जन्तेढुङ्गा गाउँपालिका'),
(45, 10510, 'Koshi', 'Khotang', 'Baraha Pokhari Rural Municipality', 'बराहपोखरी गाउँपालिका'),
(46, 10601, 'Koshi', 'Bhojpur', 'Shadananda Urban Municipality', 'षडानन्द नगरपालिका'),
(47, 10602, 'Koshi', 'Bhojpur', 'Salpa Silichho Rural Municipality', 'साल्पासिलिछो गाउँपालिका'),
(48, 10603, 'Koshi', 'Bhojpur', 'Temkemaiyum Rural Municipality', 'टेम्केमैयुङ गाउँपालिका'),
(49, 10604, 'Koshi', 'Bhojpur', 'Bhojpur Urban Municipality', 'भोजपुर नगरपालिका'),
(50, 10605, 'Koshi', 'Bhojpur', 'Arun Rural Municipality', 'अरुण गाउँपालिका'),
(51, 10606, 'Koshi', 'Bhojpur', 'Pauwa Dunma Rural Municipality', 'पौवा दुङ्मा गाउँपालिका'),
(52, 10607, 'Koshi', 'Bhojpur', 'Ramprasad Rai Rural Municipality', 'रामप्रसाद राई गाउँपालिका'),
(53, 10608, 'Koshi', 'Bhojpur', 'Hatuwagadhi Rural Municipality', 'हतुवागढी गाउँपालिका'),
(54, 10609, 'Koshi', 'Bhojpur', 'Aamchowk Rural Municipality', 'आमचोक गाउँपालिका'),
(55, 10701, 'Koshi', 'Dhankuta', 'Mahalaxmi Urban Municipality', 'महालक्ष्मी नगरपालिका'),
(56, 10702, 'Koshi', 'Dhankuta', 'Pakhribas Urban Municipality', 'पाख्रिबास नगरपालिका'),
(57, 10703, 'Koshi', 'Dhankuta', 'Chhathar Jorpati Rural Municipality', 'छथर जोरपाटी गाउँपालिका'),
(58, 10704, 'Koshi', 'Dhankuta', 'Dhankuta Urban Municipality', 'धनकुटा नगरपालिका'),
(59, 10705, 'Koshi', 'Dhankuta', 'Shahidbhumi Rural Municipality', 'सहिदभूमि गाउँपालिका'),
(60, 10706, 'Koshi', 'Dhankuta', 'Sangurigadhi Rural Municipality', 'साँगुरीगढी गाउँपालिका'),
(61, 10707, 'Koshi', 'Dhankuta', 'Chaubise Rural Municipality', 'चौविसे गाउँपालिका'),
(62, 10801, 'Koshi', 'Terhathum', 'Aatharai Rural Municipality', 'आठराई गाउँपालिका'),
(63, 10802, 'Koshi', 'Terhathum', 'Phedap Rural Municipality', 'फेदाप गाउँपालिका'),
(64, 10803, 'Koshi', 'Terhathum', 'Menchhayayem Rural Municipality', 'मेन्छयायेम गाउँपालिका'),
(65, 10804, 'Koshi', 'Terhathum', 'Myanglung Urban Municipality', 'म्याङ्गलुङ्ग नगरपालिका'),
(66, 10805, 'Koshi', 'Terhathum', 'Laligurans Urban Municipality', 'लालीगुराँस नगरपालिका'),
(67, 10806, 'Koshi', 'Terhathum', 'Chhathar Rural Municipality', 'छथर गाउँपालिका'),
(68, 10901, 'Koshi', 'Panchthar', 'Yangbarak Rural Municipality', 'याङवरक गाउँपालिका'),
(69, 10902, 'Koshi', 'Panchthar', 'Hilihan Rural Municipality', 'हिलिहाङ्ग गाउँपालिका'),
(70, 10903, 'Koshi', 'Panchthar', 'Falelung Rural Municipality', 'फालेलुङ  गाउँपालिका'),
(71, 10904, 'Koshi', 'Panchthar', 'Phidim Urban Municipality', 'फिदिम नगरपालिका'),
(72, 10905, 'Koshi', 'Panchthar', 'Falgunanda Rural Municipality', 'फाल्गुनन्द गाउँपालिका'),
(73, 10906, 'Koshi', 'Panchthar', 'Kummayak Rural Municipality', 'कुम्मायक गाउँपालिका'),
(74, 10907, 'Koshi', 'Panchthar', 'Tumbewa Rural Municipality', 'तुम्बेवा गाउँपालिका'),
(75, 10908, 'Koshi', 'Panchthar', 'Miklajung Rural Municipality', 'मिक्लाजुङ गाउँपालिका'),
(76, 11001, 'Koshi', 'Ilam', 'Mai Jogmai Rural Municipality', 'माई जोगमाई गाउँपालिका'),
(77, 11002, 'Koshi', 'Ilam', 'Sandakpur Rural Municipality', 'सन्दकपुर गाउँपालिका'),
(78, 11003, 'Koshi', 'Ilam', 'Illam Urban Municipality', 'ईलाम नगरपालिका'),
(79, 11004, 'Koshi', 'Ilam', 'Deumai Urban Municipality', 'देउमाई नगरपालिका'),
(80, 11005, 'Koshi', 'Ilam', 'Fakfokathum Rural Municipality', 'फाकफोकथुम गाउँपालिका'),
(81, 11006, 'Koshi', 'Ilam', 'Mangsebung Rural Municipality', 'माङसेबुङ गाउँपालिका'),
(82, 11007, 'Koshi', 'Ilam', 'Chulachuli Rural Municipality', 'चुलाचुली गाउँपालिका'),
(83, 11008, 'Koshi', 'Ilam', 'Mai Urban Municipality', 'माई नगरपालिका'),
(84, 11009, 'Koshi', 'Ilam', 'Suryodaya Urban Municipality', 'सूर्योदय नगरपालिका'),
(85, 11010, 'Koshi', 'Ilam', 'Rong Rural Municipality', 'रोङ गाउँपालिका'),
(86, 11101, 'Koshi', 'Jhapa', 'Mechinagar Urban Municipality', 'मेचीनगर नगरपालिका'),
(87, 11102, 'Koshi', 'Jhapa', 'Buddhashanti Rural Municipality', 'बुद्धशान्ति गाउँपालिका'),
(88, 11103, 'Koshi', 'Jhapa', 'Arjundhara Urban Municipality', 'अर्जुनधारा नगरपालिका'),
(89, 11104, 'Koshi', 'Jhapa', 'Kankai Urban Municipality', 'कन्काई नगरपालिका'),
(90, 11105, 'Koshi', 'Jhapa', 'Shivasatakshi Urban Municipality', 'शिवसताक्षी नगरपालिका'),
(91, 11106, 'Koshi', 'Jhapa', 'Kamal Rural Municipality', 'कमल गाउँपालिका'),
(92, 11107, 'Koshi', 'Jhapa', 'Damak Urban Municipality', 'दमक नगरपालिका'),
(93, 11108, 'Koshi', 'Jhapa', 'Gauradaha Urban Municipality', 'गौरादह नगरपालिका'),
(94, 11109, 'Koshi', 'Jhapa', 'Gauriganj Rural Municipality', 'गौरिगञ्ज गाउँपालिका'),
(95, 11110, 'Koshi', 'Jhapa', 'Jhapa Rural Municipality', 'झापा गाउँपालिका'),
(96, 11111, 'Koshi', 'Jhapa', 'Barhadashi Rural Municipality', 'बाह्रदशी गाउँपालिका'),
(97, 11112, 'Koshi', 'Jhapa', 'Birtamod Urban Municipality', 'बिर्तामोड नगरपालिका'),
(98, 11113, 'Koshi', 'Jhapa', 'Haldibari Rural Municipality', 'हल्दीबारी गाउँपालिका'),
(99, 11114, 'Koshi', 'Jhapa', 'Bhadrapur Urban Municipality', 'भद्रपुर नगरपालिका'),
(100, 11115, 'Koshi', 'Jhapa', 'Kachanakawal Rural Municipality', 'कचनकवल गाउँपालिका'),
(101, 11201, 'Koshi', 'Morang', 'Miklajung Rural Municipality', 'मिक्लाजुङ गाउँपालिका'),
(102, 11202, 'Koshi', 'Morang', 'Letang Urban Municipality', 'लेटाङ नगरपालिका'),
(103, 11203, 'Koshi', 'Morang', 'Kerabari Rural Municipality', 'केराबारी गाउँपालिका'),
(104, 11204, 'Koshi', 'Morang', 'Sundarharaicha Urban Municipality', 'सुन्दरहरैंचा नगरपालिका'),
(105, 11205, 'Koshi', 'Morang', 'Belbari Urban Municipality', 'बेलबारी नगरपालिका'),
(106, 11206, 'Koshi', 'Morang', 'Kanepokhari Rural Municipality', 'कानेपोखरी गाउँपालिका'),
(107, 11207, 'Koshi', 'Morang', 'Pathari Shanishchare Urban Municipality', 'पथरी शनिश्चरे नगरपालिका'),
(108, 11208, 'Koshi', 'Morang', 'Urlabari Urban Municipality', 'उर्लाबारी नगरपालिका'),
(109, 11209, 'Koshi', 'Morang', 'Ratuwamai Urban Municipality', 'रतुवामाई नगरपालिका'),
(110, 11210, 'Koshi', 'Morang', 'Sunwarshi Urban Municipality', 'सुनवर्षी नगरपालिका'),
(111, 11211, 'Koshi', 'Morang', 'Rangeli Urban Municipality', 'रंगेली नगरपालिका'),
(112, 11212, 'Koshi', 'Morang', 'Gramthan Rural Municipality', 'ग्रामथान गाउँपालिका'),
(113, 11213, 'Koshi', 'Morang', 'Budhiganga Rural Municipality', 'बुढीगंगा गाउँपालिका'),
(114, 11214, 'Koshi', 'Morang', 'Biratnagar Metropolitian City', 'बिराटनगर महानगरपालिका'),
(115, 11215, 'Koshi', 'Morang', 'Katahari Rural Municipality', 'कटहरी गाउँपालिका'),
(116, 11216, 'Koshi', 'Morang', 'Dhanapalthan Rural Municipality', 'धनपालथान गाउँपालिका'),
(117, 11217, 'Koshi', 'Morang', 'Jahada Rural Municipality', 'जहदा गाउँपालिका'),
(118, 11301, 'Koshi', 'Sunsari', 'Dharan Sub-Metropolitian City', 'धरान उपमहानगरपालिका'),
(119, 11302, 'Koshi', 'Sunsari', 'Barahachhetra Urban Municipality', 'बराहक्षेत्र नगरपालिका'),
(120, 11303, 'Koshi', 'Sunsari', 'Koshi Rural Municipality', 'कोशी गाउँपालिका'),
(121, 11304, 'Koshi', 'Sunsari', 'Bhokraha Narsingh Rural Municipality', 'भोक्राहा नरसिंह गाउँपालिका'),
(122, 11305, 'Koshi', 'Sunsari', 'Ramdhuni Urban Municipality', 'रामधुनी नगरपालिका'),
(123, 11306, 'Koshi', 'Sunsari', 'Itahari Sub-Metropolitian City', 'ईटहरी उपमहानगरपालिका'),
(124, 11307, 'Koshi', 'Sunsari', 'Duhabi Urban Municipality', 'दुहबी नगरपालिका'),
(125, 11308, 'Koshi', 'Sunsari', 'Gadhi Rural Municipality', 'गढी गाउँपालिका'),
(126, 11309, 'Koshi', 'Sunsari', 'Inaruwa Urban Municipality', 'इनरुवा नगरपालिका'),
(127, 11310, 'Koshi', 'Sunsari', 'Harinagar Rural Municipality', 'हरिनगर गाउँपालिका'),
(128, 11311, 'Koshi', 'Sunsari', 'Dewangunj Rural Municipality', 'देवानगन्ज गाउँपालिका'),
(129, 11312, 'Koshi', 'Sunsari', 'Barju Rural Municipality', 'बर्जु गाउँपालिका'),
(130, 11401, 'Koshi', 'Udayapur', 'Belaka Urban Municipality', 'बेलका नगरपालिका'),
(131, 11402, 'Koshi', 'Udayapur', 'Chaudandigadhi Urban Municipality', 'चौदण्डीगढी नगरपालिका'),
(132, 11403, 'Koshi', 'Udayapur', 'Triyuga Urban Municipality', 'त्रियुगा नगरपालिका'),
(133, 11404, 'Koshi', 'Udayapur', 'Rautamai Rural Municipality', 'रौतामाई गाउँपालिका'),
(134, 11405, 'Koshi', 'Udayapur', 'Limchungbung Rural Municipality', ' लिम्चुङबुङ  गाउँपालिका'),
(135, 11406, 'Koshi', 'Udayapur', 'Tapli Rural Municipality', 'ताप्ली गाउँपालिका'),
(136, 11407, 'Koshi', 'Udayapur', 'Katari Urban Municipality', 'कटारी नगरपालिका'),
(137, 11408, 'Koshi', 'Udayapur', 'Udayapurgadhi Rural Municipality', 'उदयपुरगढी गाउँपालिका'),
(138, 20101, 'Madhesh', 'Saptari', 'Saptakoshi Urban Municipality', 'सप्तकोशी नगरपालिका'),
(139, 20102, 'Madhesh', 'Saptari', 'Kanchanrup Urban Municipality', 'कन्चनरुप नगरपालिका'),
(140, 20103, 'Madhesh', 'Saptari', 'Agnisair Krishna Sabaran Rural Municipality', 'अग्निसाइर कृष्ण सवरन गाउँपालिका'),
(141, 20104, 'Madhesh', 'Saptari', 'Rupani Rural Municipality', 'रुपनी गाउँपालिका'),
(142, 20105, 'Madhesh', 'Saptari', 'Shambhunath Urban Municipality', 'शम्भुनाथ नगरपालिका'),
(143, 20106, 'Madhesh', 'Saptari', 'Khadak Urban Municipality', 'खडक नगरपालिका'),
(144, 20107, 'Madhesh', 'Saptari', 'Surunga Urban Municipality', 'सुरुङ्गा नगरपालिका'),
(145, 20108, 'Madhesh', 'Saptari', 'Balan-Bihul Rural Municipality', 'बलान बिहुल गाउँपालिका'),
(146, 20109, 'Madhesh', 'Saptari', 'Bode Barsain Urban Municipality', 'बोदेबरसाईन नगरपालिका'),
(147, 20110, 'Madhesh', 'Saptari', 'Dakneshwori Urban Municipality', 'डाक्नेश्वरी नगरपालिका'),
(148, 20111, 'Madhesh', 'Saptari', 'Rajgadh Rural Municipality', 'राजगढ गाउँपालिका'),
(149, 20112, 'Madhesh', 'Saptari', 'Bishnupur Rural Municipality', 'बिष्णुपुर गाउँपालिका'),
(150, 20113, 'Madhesh', 'Saptari', 'Rajbiraj Urban Municipality', 'राजविराज नगरपालिका'),
(151, 20114, 'Madhesh', 'Saptari', 'Mahadewa Rural Municipality', 'महादेवा गाउँपालिका'),
(152, 20115, 'Madhesh', 'Saptari', 'Tirahut Rural Municipality', 'तिरहुत गाउँपालिका'),
(153, 20116, 'Madhesh', 'Saptari', 'Hanumannagar Kankalini Urban Municipality', 'हनुमाननगर कङ्कालिनी नगरपालिका'),
(154, 20117, 'Madhesh', 'Saptari', 'Tilathi Koiladi Rural Municipality', 'तिलाठी कोईलाडी गाउँपालिका'),
(155, 20118, 'Madhesh', 'Saptari', 'Chhinnamasta Rural Municipality', 'छिन्नमस्ता गाउँपालिका'),
(156, 20201, 'Madhesh', 'Siraha', 'Lahan Urban Municipality', 'लहान नगरपालिका'),
(157, 20202, 'Madhesh', 'Siraha', 'Dhangadhimai Urban Municipality', 'धनगढीमाई नगरपालिका'),
(158, 20203, 'Madhesh', 'Siraha', 'Golbazar Urban Municipality', 'गोलबजार नगरपालिका'),
(159, 20204, 'Madhesh', 'Siraha', 'Mirchaiya Urban Municipality', 'मिर्चेया नगरपालिका'),
(160, 20205, 'Madhesh', 'Siraha', 'Karjanha Urban Municipality', 'कर्जन्हा नगरपालिका'),
(161, 20206, 'Madhesh', 'Siraha', 'Kalyanpur Urban Municipality', 'कल्याणपुर नगरपालिका'),
(162, 20207, 'Madhesh', 'Siraha', 'Naraha Rural Municipality', 'नरहा गाउँपालिका'),
(163, 20208, 'Madhesh', 'Siraha', 'Bishnupur Rural Municipality', 'बिष्णुपुर गाउँपालिका'),
(164, 20209, 'Madhesh', 'Siraha', 'Arnama Rural Municipality', 'अर्नमा गाउँपालिका'),
(165, 20210, 'Madhesh', 'Siraha', 'Sukhipur Urban Municipality', 'सुखीपुर नगरपालिका'),
(166, 20211, 'Madhesh', 'Siraha', 'Laxmipur Patari Rural Municipality', 'लक्ष्मीपुर पतारी गाउँपालिका'),
(167, 20212, 'Madhesh', 'Siraha', 'Sakhuwa Nankarkatti Rural Municipality', 'सखुवानान्कारकट्टी गाउँपालिका'),
(168, 20213, 'Madhesh', 'Siraha', 'Bhagawanpur Rural Municipality', 'भगवानपुर गाउँपालिका'),
(169, 20214, 'Madhesh', 'Siraha', 'Nawarajpur Rural Municipality', 'नवराजपुर गाउँपालिका'),
(170, 20215, 'Madhesh', 'Siraha', 'Bariyarpatti Rural Municipality', 'बरियारपट्टी गाउँपालिका'),
(171, 20216, 'Madhesh', 'Siraha', 'Aurahi Rural Municipality', 'औरही गाउँपालिका'),
(172, 20217, 'Madhesh', 'Siraha', 'Siraha Urban Municipality', 'सिराहा नगरपालिका'),
(173, 20301, 'Madhesh', 'Dhanusa', 'Ganeshman Charnath Urban Municipality', 'गणेशमान चारनाथ नगरपालिका'),
(174, 20302, 'Madhesh', 'Dhanusa', 'Dhanushadham Urban Municipality', 'धनुषाधाम नगरपालिका'),
(175, 20303, 'Madhesh', 'Dhanusa', 'Mithila Urban Municipality', 'मिथिला नगरपालिका'),
(176, 20304, 'Madhesh', 'Dhanusa', 'Bateshwor Rural Municipality', 'बटेश्वर गाउँपालिका'),
(177, 20305, 'Madhesh', 'Dhanusa', 'Chhireshwornath Urban Municipality', 'क्षिरेश्वरनाथ नगरपालिका'),
(178, 20306, 'Madhesh', 'Dhanusa', 'Laxminiya Rural Municipality', 'लक्ष्मीनिया गाउँपालिका'),
(179, 20307, 'Madhesh', 'Dhanusa', 'Mithila Bihari Urban Municipality', 'मिथिला बिहारी नगरपालिका'),
(180, 20308, 'Madhesh', 'Dhanusa', 'Hansapur Urban Municipality', 'हंसपुर नगरपालिका'),
(181, 20309, 'Madhesh', 'Dhanusa', 'Sabaila Urban Municipality', 'सबैला नगरपालिका'),
(182, 20310, 'Madhesh', 'Dhanusa', 'Shahidnagar Urban Municipality', 'शहीदनगर नगरपालिका'),
(183, 20311, 'Madhesh', 'Dhanusa', 'Kamala Urban Municipality', 'कमला नगरपालिका'),
(184, 20312, 'Madhesh', 'Dhanusa', 'Janak Nandini Rural Municipality', 'जनक नन्दिनी गाउँपालिका'),
(185, 20313, 'Madhesh', 'Dhanusa', 'Bideha Urban Municipality', 'बिदेह नगरपालिका'),
(186, 20314, 'Madhesh', 'Dhanusa', 'Aurahi Rural Municipality', 'औरही गाउँपालिका'),
(187, 20315, 'Madhesh', 'Dhanusa', 'Janakpurdham Sub-Metropolitian City', 'जनकपुरधाम उपमहानगरपालिका'),
(188, 20316, 'Madhesh', 'Dhanusa', 'Dhanauji Rural Municipality', 'धनौजी गाउँपालिका'),
(189, 20317, 'Madhesh', 'Dhanusa', 'Nagarain Urban Municipality', 'नगराइन नगरपालिका'),
(190, 20318, 'Madhesh', 'Dhanusa', 'Mukhiyapatti Musaharmiya Rural Municipality', 'मुखियापट्टी मुसहरमिया गाउँपालिका'),
(191, 20401, 'Madhesh', 'Mahottari', 'Bardibas Urban Municipality', 'बर्दिबास नगरपालिका'),
(192, 20402, 'Madhesh', 'Mahottari', 'Gaushala Urban Municipality', 'गौशाला नगरपालिका'),
(193, 20403, 'Madhesh', 'Mahottari', 'Sonama Rural Municipality', 'सोनमा गाउँपालिका'),
(194, 20404, 'Madhesh', 'Mahottari', 'Aurahi Urban Municipality', 'औरही नगरपालिका'),
(195, 20405, 'Madhesh', 'Mahottari', 'Bhangaha Urban Municipality', 'भँगाहा नगरपालिका'),
(196, 20406, 'Madhesh', 'Mahottari', 'Loharpatti Urban Municipality', 'लोहरपट्टी नगरपालिका'),
(197, 20407, 'Madhesh', 'Mahottari', 'Balawa Urban Municipality', 'बलवा नगरपालिका'),
(198, 20408, 'Madhesh', 'Mahottari', 'Ram Gopalpur Urban Municipality', 'राम गोपालपुर नगरपालिका'),
(199, 20409, 'Madhesh', 'Mahottari', 'Samsi Rural Municipality', 'साम्सी गाउँपालिका'),
(200, 20410, 'Madhesh', 'Mahottari', 'Manara Shisawa Urban Municipality', 'मनरा शिसवा नगरपालिका'),
(201, 20411, 'Madhesh', 'Mahottari', 'Ekadara Rural Municipality', 'एकडारा गाउँपालिका'),
(202, 20412, 'Madhesh', 'Mahottari', 'Mahottari Rural Municipality', 'महोत्तरी गाउँपालिका'),
(203, 20413, 'Madhesh', 'Mahottari', 'Pipara Rural Municipality', 'पिपरा गाउँपालिका'),
(204, 20414, 'Madhesh', 'Mahottari', 'Matihani Urban Municipality', 'मटिहानी नगरपालिका'),
(205, 20415, 'Madhesh', 'Mahottari', 'Jaleshwor Urban Municipality', 'जलेश्वर नगरपालिका'),
(206, 20501, 'Madhesh', 'Sarlahi', 'Lalbandi Urban Municipality', 'लालबन्दी नगरपालिका'),
(207, 20502, 'Madhesh', 'Sarlahi', 'Hariwan Urban Municipality', 'हरिवन नगरपालिका'),
(208, 20503, 'Madhesh', 'Sarlahi', 'Bagmati Urban Municipality', 'बागमती नगरपालिका'),
(209, 20504, 'Madhesh', 'Sarlahi', 'Barahathawa Urban Municipality', 'बरहथवा नगरपालिका'),
(210, 20505, 'Madhesh', 'Sarlahi', 'Haripur Urban Municipality', 'हरिपुर नगरपालिका'),
(211, 20506, 'Madhesh', 'Sarlahi', 'Ishworpur Urban Municipality', 'ईश्वरपुर नगरपालिका'),
(212, 20507, 'Madhesh', 'Sarlahi', 'Haripurwa Urban Municipality', 'हरिपुर्वा नगरपालिका'),
(213, 20508, 'Madhesh', 'Sarlahi', 'Parsa Rural Municipality', 'पर्सा गाउँपालिका'),
(214, 20509, 'Madhesh', 'Sarlahi', 'Brahmapuri Rural Municipality', 'ब्रह्मपुरी गाउँपालिका'),
(215, 20510, 'Madhesh', 'Sarlahi', 'Chandranagar Rural Municipality', 'चन्द्रनगर गाउँपालिका'),
(216, 20511, 'Madhesh', 'Sarlahi', 'Kabilashi Urban Municipality', 'कविलासी नगरपालिका'),
(217, 20512, 'Madhesh', 'Sarlahi', 'Chakraghatta Rural Municipality', 'चक्रघट्टा गाउँपालिका'),
(218, 20513, 'Madhesh', 'Sarlahi', 'Basbariya Rural Municipality', 'बसबरिया गाउँपालिका'),
(219, 20514, 'Madhesh', 'Sarlahi', 'Dhanakaul Rural Municipality', 'धनकौल गाउँपालिका'),
(220, 20515, 'Madhesh', 'Sarlahi', 'Ramnagar Rural Municipality', 'रामनगर गाउँपालिका'),
(221, 20516, 'Madhesh', 'Sarlahi', 'Balara Urban Municipality', 'बलरा नगरपालिका'),
(222, 20517, 'Madhesh', 'Sarlahi', 'Godaita Urban Municipality', 'गोडैटा नगरपालिका'),
(223, 20518, 'Madhesh', 'Sarlahi', 'Bishnu Rural Municipality', 'विष्णु गाउँपालिका'),
(224, 20519, 'Madhesh', 'Sarlahi', 'Kaudena Rural Municipality', 'कौडेना गाउँपालिका'),
(225, 20520, 'Madhesh', 'Sarlahi', 'Malangawa Urban Municipality', 'मलंगवा नगरपालिका'),
(226, 20601, 'Madhesh', 'Rautahat', 'Chandrapur Urban Municipality', 'चन्द्रपुर नगरपालिका'),
(227, 20602, 'Madhesh', 'Rautahat', 'Gujara Urban Municipality', 'गुजरा नगरपालिका'),
(228, 20603, 'Madhesh', 'Rautahat', 'Phatuwa Bijayapur Urban Municipality', 'फतुवा बिजयपुर नगरपालिका'),
(229, 20604, 'Madhesh', 'Rautahat', 'Katahariya Urban Municipality', 'कटहरिया नगरपालिका'),
(230, 20605, 'Madhesh', 'Rautahat', 'Brindaban Urban Municipality', 'बृन्दावन नगरपालिका'),
(231, 20606, 'Madhesh', 'Rautahat', 'Gadhimai Urban Municipality', 'गढीमाई नगरपालिका'),
(232, 20607, 'Madhesh', 'Rautahat', 'Madhav Narayan Urban Municipality', 'माधव नारायण नगरपालिका'),
(233, 20608, 'Madhesh', 'Rautahat', 'Garuda Urban Municipality', 'गरुडा नगरपालिका'),
(234, 20609, 'Madhesh', 'Rautahat', 'Dewahi Gonahi Urban Municipality', 'देवाही गोनाही नगरपालिका'),
(235, 20610, 'Madhesh', 'Rautahat', 'Maulapur Urban Municipality', 'मौलापुर नगरपालिका'),
(236, 20611, 'Madhesh', 'Rautahat', 'Boudhimai Urban Municipality', 'बौधीमाई नगरपालिका'),
(237, 20612, 'Madhesh', 'Rautahat', 'Paroha Urban Municipality', 'परोहा नगरपालिका'),
(238, 20613, 'Madhesh', 'Rautahat', 'Rajpur Urban Municipality', 'राजपुर नगरपालिका'),
(239, 20614, 'Madhesh', 'Rautahat', 'Yamunamai Rural Municipality', 'यमुनामाई गाउँपालिका'),
(240, 20615, 'Madhesh', 'Rautahat', 'Durga Bhagawati Rural Municipality', 'दुर्गा भगवती गाउँपालिका'),
(241, 20616, 'Madhesh', 'Rautahat', 'Rajdevi Urban Municipality', 'राजदेवी नगरपालिका'),
(242, 20617, 'Madhesh', 'Rautahat', 'Gaur Urban Municipality', 'गौर नगरपालिका'),
(243, 20618, 'Madhesh', 'Rautahat', 'Ishanath Urban Municipality', 'ईशनाथ नगरपालिका'),
(244, 20701, 'Madhesh', 'Bara', 'Nijagadh Urban Municipality', 'निजगढ नगरपालिका'),
(245, 20702, 'Madhesh', 'Bara', 'Kolhabi Urban Municipality', 'कोल्हवी नगरपालिका'),
(246, 20703, 'Madhesh', 'Bara', 'Jitpur Simara Sub-Metropolitian City', 'जीतपुर सिमरा उपमहानगरपालिका'),
(247, 20704, 'Madhesh', 'Bara', 'Parawanipur Rural Municipality', 'परवानीपुर गाउँपालिका'),
(248, 20705, 'Madhesh', 'Bara', 'Prasauni Rural Municipality', 'प्रसौनी गाउँपालिका'),
(249, 20706, 'Madhesh', 'Bara', 'Bishrampur Rural Municipality', 'विश्रामपुर गाउँपालिका'),
(250, 20707, 'Madhesh', 'Bara', 'Pheta Rural Municipality', 'फेटा गाउँपालिका'),
(251, 20708, 'Madhesh', 'Bara', 'Kalaiya Sub-Metropolitian City', 'कलैया उपमहानगरपालिका'),
(252, 20709, 'Madhesh', 'Bara', 'Karaiyamai Rural Municipality', 'करैयामाई गाउँपालिका'),
(253, 20710, 'Madhesh', 'Bara', 'Baragadhi Rural Municipality', 'बारागढी गाउँपालिका'),
(254, 20711, 'Madhesh', 'Bara', 'Aadarsha Kotwal Rural Municipality', 'आदर्श कोटवाल गाउँपालिका'),
(255, 20712, 'Madhesh', 'Bara', 'Simroungadh Urban Municipality', 'सिम्रौनगढ नगरपालिका'),
(256, 20713, 'Madhesh', 'Bara', 'Pacharauta Urban Municipality', 'पचरौता नगरपालिका'),
(257, 20714, 'Madhesh', 'Bara', 'Mahagadhimai Urban Municipality', 'महागढीमाई नगरपालिका'),
(258, 20715, 'Madhesh', 'Bara', 'Devtal Rural Municipality', 'देवताल गाउँपालिका'),
(259, 20716, 'Madhesh', 'Bara', 'Subarna Rural Municipality', 'सुवर्ण गाउँपालिका'),
(260, 20801, 'Madhesh', 'Parsa', 'Thori Rural Municipality', 'ठोरी (सुवर्णपुर) गाउँपालिका'),
(261, 20802, 'Madhesh', 'Parsa', 'Jirabhawani Rural Municipality', 'जिराभवानी गाउँपालिका'),
(262, 20803, 'Madhesh', 'Parsa', 'Jagarnathpur Rural Municipality', 'जगरनाथपुर गाउँपालिका'),
(263, 20804, 'Madhesh', 'Parsa', 'Paterwa Sugauli Rural Municipality', 'पटेर्वा सुगौली गाउँपालिका'),
(264, 20805, 'Madhesh', 'Parsa', 'Sakhuwa Prasauni Rural Municipality', 'सखुवा प्रसौनी गाउँपालिका'),
(265, 20806, 'Madhesh', 'Parsa', 'Parsagadhi Urban Municipality', 'पर्सागढी नगरपालिका'),
(266, 20807, 'Madhesh', 'Parsa', 'Birgunj Metropolitian City', 'बिरगन्ज महानगरपालिका'),
(267, 20808, 'Madhesh', 'Parsa', 'Bahudarmai Urban Municipality', 'बहुदरमाई नगरपालिका'),
(268, 20809, 'Madhesh', 'Parsa', 'Pokhariya Urban Municipality', 'पोखरिया नगरपालिका'),
(269, 20810, 'Madhesh', 'Parsa', 'Kalikamai Rural Municipality', 'कालिकामाई गाउँपालिका'),
(270, 20811, 'Madhesh', 'Parsa', 'Dhobini Rural Municipality', 'धोबीनी गाउँपालिका'),
(271, 20812, 'Madhesh', 'Parsa', 'Chhipaharmai Rural Municipality', 'छिपहरमाई गाउँपालिका'),
(272, 20813, 'Madhesh', 'Parsa', 'Pakaha Mainpur Rural Municipality', 'पकाहा मैनपुर गाउँपालिका'),
(273, 20814, 'Madhesh', 'Parsa', 'Bindabasini Rural Municipality', 'बिन्दवासिनी गाउँपालिका'),
(274, 30101, 'Bagmati', 'Dolakha', 'Gaurishankar Rural Municipality', 'गौरिशंकर गाउँपालिका'),
(275, 30102, 'Bagmati', 'Dolakha', 'Bigu Rural Municipality', 'बिगु गाउँपालिका'),
(276, 30103, 'Bagmati', 'Dolakha', 'Kalinchowk Rural Municipality', 'कालिन्चोक गाउँपालिका'),
(277, 30104, 'Bagmati', 'Dolakha', 'Baiteshwor Rural Municipality', 'बैतेश्वर  गाउँपालिका'),
(278, 30105, 'Bagmati', 'Dolakha', 'Jiri Urban Municipality', 'जिरी नगरपालिका'),
(279, 30106, 'Bagmati', 'Dolakha', 'Tamakoshi Rural Municipality', 'तामाकोशी गाउँपालिका'),
(280, 30107, 'Bagmati', 'Dolakha', 'Melung Rural Municipality', 'मेलुङ्ग गाउँपालिका'),
(281, 30108, 'Bagmati', 'Dolakha', 'Shailung Rural Municipality', 'शैलुड० गाउँपालिका'),
(282, 30109, 'Bagmati', 'Dolakha', 'Bhimeshwor Urban Municipality', 'भिमेश्वर नगरपालिका'),
(283, 30201, 'Bagmati', 'Sindhupalchok', 'Bhotekoshi Rural Municipality', 'भोटेकोशी गाउँपालिका'),
(284, 30202, 'Bagmati', 'Sindhupalchok', 'Jugal Rural Municipality', 'जुगल गाउँपालिका'),
(285, 30203, 'Bagmati', 'Sindhupalchok', 'Panchpokhari Thangpal Rural Municipality', 'पाँचपोखरी थाड०पाल गाउँपालिका'),
(286, 30204, 'Bagmati', 'Sindhupalchok', 'Helambu Rural Municipality', 'हेलम्बु गाउँपालिका'),
(287, 30205, 'Bagmati', 'Sindhupalchok', 'Melanchi Urban Municipality', 'मेलम्ची नगरपालिका'),
(288, 30206, 'Bagmati', 'Sindhupalchok', 'Indrawoti Rural Municipality', 'ईन्द्रावती गाउँपालिका'),
(289, 30207, 'Bagmati', 'Sindhupalchok', 'Choutara Sangachowkgadhi Urban Municipality', 'चौतारा साँगाचोकगढी नगरपालिका'),
(290, 30208, 'Bagmati', 'Sindhupalchok', 'Balephi Rural Municipality', 'बलेफी गाउँपालिका'),
(291, 30209, 'Bagmati', 'Sindhupalchok', 'Bahrabise Urban Municipality', 'बाह्रबिसे नगरपालिका'),
(292, 30210, 'Bagmati', 'Sindhupalchok', 'Tripurasundari Rural Municipality', 'त्रिपुरासुन्दरी गाउँपालिका'),
(293, 30211, 'Bagmati', 'Sindhupalchok', 'Lisankhu Pakhar Rural Municipality', 'लिसंखु पाखर गाउँपालिका'),
(294, 30212, 'Bagmati', 'Sindhupalchok', 'Sunkoshi Rural Municipality', 'सुनकोशी गाउँपालिका'),
(295, 30301, 'Bagmati', 'Rasuwa', 'Gosaikunda Rural Municipality', 'गोसाईकुण्ड गाउँपालिका'),
(296, 30302, 'Bagmati', 'Rasuwa', 'Aamachhodingmo Rural Municipality', 'आमाछोदिङमो गाउँपालिका'),
(297, 30303, 'Bagmati', 'Rasuwa', 'Uttargaya Rural Municipality', 'उत्तरगया गाउँपालिका'),
(298, 30304, 'Bagmati', 'Rasuwa', 'Shuva Kalika Rural Municipality', 'शुभ कालीका गाउँपालिका'),
(299, 30305, 'Bagmati', 'Rasuwa', 'Naukunda Rural Municipality', 'नौकुण्ड गाउँपालिका'),
(300, 30401, 'Bagmati', 'Dhading', 'Rubi Valley Rural Municipality', 'रुबी भ्याली गाउँपालिका'),
(301, 30402, 'Bagmati', 'Dhading', 'Khaniyabas Rural Municipality', 'खनियाबास गाउँपालिका'),
(302, 30403, 'Bagmati', 'Dhading', 'Ganga Jamuna Rural Municipality', 'गंङ्गा जमुना गाउँपालिका'),
(303, 30404, 'Bagmati', 'Dhading', 'Tripurasundari Rural Municipality', 'त्रिपुरासुन्दरी गाउँपालिका'),
(304, 30405, 'Bagmati', 'Dhading', 'Netrawati Dabjong Rural Municipality', 'नेत्रावती डबजोङ गाउँपालिका'),
(305, 30406, 'Bagmati', 'Dhading', 'Nilkhantha Urban Municipality', 'नीलकण्ठ नगरपालिका'),
(306, 30407, 'Bagmati', 'Dhading', 'Jwalamukhi Rural Municipality', 'ज्वालामुखी गाउँपालिका'),
(307, 30408, 'Bagmati', 'Dhading', 'Siddhalek Rural Municipality', 'सिद्धलेक गाउँपालिका'),
(308, 30409, 'Bagmati', 'Dhading', 'Benighat Rorang Rural Municipality', 'बेनीघाट रोराङ्ग गाउँपालिका'),
(309, 30410, 'Bagmati', 'Dhading', 'Gajuri Rural Municipality', 'गजुरी गाउँपालिका'),
(310, 30411, 'Bagmati', 'Dhading', 'Galchhi Rural Municipality', 'गल्छी गाउँपालिका'),
(311, 30412, 'Bagmati', 'Dhading', 'Thakre Rural Municipality', 'थाक्रे गाउँपालिका'),
(312, 30413, 'Bagmati', 'Dhading', 'Dhunibenshi Urban Municipality', 'धुनीबेंशी नगरपालिका'),
(313, 30501, 'Bagmati', 'Nuwakot', 'Dupcheshwor Rural Municipality', 'दुप्चेश्वर गाउँपालिका'),
(314, 30502, 'Bagmati', 'Nuwakot', 'Tadi Rural Municipality', 'तादी गाउँपालिका'),
(315, 30503, 'Bagmati', 'Nuwakot', 'Suryagadhi Rural Municipality', 'सुर्यगढी गाउँपालिका'),
(316, 30504, 'Bagmati', 'Nuwakot', 'Bidur Urban Municipality', 'बिदुर नगरपालिका'),
(317, 30505, 'Bagmati', 'Nuwakot', 'Kispang Rural Municipality', 'किस्पाङ्ग गाउँपालिका'),
(318, 30506, 'Bagmati', 'Nuwakot', 'Myagang Rural Municipality', 'म्यगङ गाउँपालिका'),
(319, 30507, 'Bagmati', 'Nuwakot', 'Tarakeshwor Rural Municipality', 'तारकेश्वर गाउँपालिका'),
(320, 30508, 'Bagmati', 'Nuwakot', 'Belkotgadhi Urban Municipality', 'बेलकोटगढी नगरपालिका'),
(321, 30509, 'Bagmati', 'Nuwakot', 'Likhu Rural Municipality', 'लिखु गाउँपालिका'),
(322, 30510, 'Bagmati', 'Nuwakot', 'Panchakanya Rural Municipality', 'पन्चकन्या गाउँपालिका'),
(323, 30511, 'Bagmati', 'Nuwakot', 'Shivapuri Rural Municipality', 'शिवपुरी गाउँपालिका'),
(324, 30512, 'Bagmati', 'Nuwakot', 'Kakani Rural Municipality', 'ककनी गाउँपालिका'),
(325, 30601, 'Bagmati', 'Kathmandu', 'Shankharapur Urban Municipality', 'शंङ्खरापुर नगरपालिका'),
(326, 30602, 'Bagmati', 'Kathmandu', 'Kageshwori Manahara Urban Municipality', 'कागेश्वरी मनहरा नगरपालिका'),
(327, 30603, 'Bagmati', 'Kathmandu', 'Gokarneshwor Urban Municipality', 'गोकर्णेश्वर नगरपालिका'),
(328, 30604, 'Bagmati', 'Kathmandu', 'Budhanilkhantha Urban Municipality', 'बुढानिलकण्ठ नगरपालिका'),
(329, 30605, 'Bagmati', 'Kathmandu', 'Tokha Urban Municipality', 'टोखा नगरपालिका'),
(330, 30606, 'Bagmati', 'Kathmandu', 'Tarakeshwor Urban Municipality', 'तारकेश्वर नगरपालिका'),
(331, 30607, 'Bagmati', 'Kathmandu', 'Nagarjun Urban Municipality', 'नागार्जुन नगरपालिका'),
(332, 30608, 'Bagmati', 'Kathmandu', 'Kathmandu Metropolitian City', 'काठमाण्डौ महानगरपालिका'),
(333, 30609, 'Bagmati', 'Kathmandu', 'Kirtipur Urban Municipality', 'किर्तिपुर नगरपालिका'),
(334, 30610, 'Bagmati', 'Kathmandu', 'Chandragiri Urban Municipality', 'चन्द्रागिरी नगरपालिका'),
(335, 30611, 'Bagmati', 'Kathmandu', 'Dakshinkali Urban Municipality', 'दक्षिणकाली नगरपालिका'),
(336, 30701, 'Bagmati', 'Bhaktapur', 'Changunarayan Urban Municipality', 'चाँगुनारायण नगरपालिका'),
(337, 30702, 'Bagmati', 'Bhaktapur', 'Bhaktapur Urban Municipality', 'भक्तपुर नगरपालिका'),
(338, 30703, 'Bagmati', 'Bhaktapur', 'Madhyapur Thimi Urban Municipality', 'मध्यपुर थिमी नगरपालिका'),
(339, 30704, 'Bagmati', 'Bhaktapur', 'Suryabinayak Urban Municipality', 'सूर्यविनायक नगरपालिका'),
(340, 30801, 'Bagmati', 'Lalitpur', 'Mahalaxmi Urban Municipality', 'महालक्ष्मी नगरपालिका'),
(341, 30802, 'Bagmati', 'Lalitpur', 'Lalitpur Metropolitian City', 'ललितपुर महानगरपालिका'),
(342, 30803, 'Bagmati', 'Lalitpur', 'Godawari Urban Municipality', 'गोदावरी नगरपालिका'),
(343, 30804, 'Bagmati', 'Lalitpur', 'Konjyosom Rural Municipality', 'कोन्ज्योसोम गाउँपालिका'),
(344, 30805, 'Bagmati', 'Lalitpur', 'Mahankal Rural Municipality', 'महाङ्काल गाउँपालिका'),
(345, 30806, 'Bagmati', 'Lalitpur', 'Bagmati Rural Municipality', 'बाग्मती गाउँपालिका'),
(346, 30901, 'Bagmati', 'Kavrepalanchok', 'Chauri Deurali Rural Municipality', 'चौरीदेउराली गाउँपालिका'),
(347, 30902, 'Bagmati', 'Kavrepalanchok', 'Bhumlu Rural Municipality', 'भुम्लु गाउँपालिका'),
(348, 30903, 'Bagmati', 'Kavrepalanchok', 'Mandan Deupur Urban Municipality', 'मण्डन देउपुर नगरपालिका'),
(349, 30904, 'Bagmati', 'Kavrepalanchok', 'Banepa Urban Municipality', 'बनेपा नगरपालिका'),
(350, 30905, 'Bagmati', 'Kavrepalanchok', 'Dhulikhel Urban Municipality', 'धुलिखेल नगरपालिका'),
(351, 30906, 'Bagmati', 'Kavrepalanchok', 'Panchkhal Urban Municipality', 'पाँचखाल नगरपालिका'),
(352, 30907, 'Bagmati', 'Kavrepalanchok', 'Temal Rural Municipality', 'तेमाल गाउँपालिका'),
(353, 30908, 'Bagmati', 'Kavrepalanchok', 'Namobuddha Urban Municipality', 'नमोबुद्ध नगरपालिका'),
(354, 30909, 'Bagmati', 'Kavrepalanchok', 'Panauti Urban Municipality', 'पनौती नगरपालिका'),
(355, 30910, 'Bagmati', 'Kavrepalanchok', 'Bethanchowk Rural Municipality', 'बेथानचोक गाउँपालिका'),
(356, 30911, 'Bagmati', 'Kavrepalanchok', 'Roshi Rural Municipality', 'रोशी गाउँपालिका'),
(357, 30912, 'Bagmati', 'Kavrepalanchok', 'Mahabharat Rural Municipality', 'महाभारत गाउँपालिका'),
(358, 30913, 'Bagmati', 'Kavrepalanchok', 'Khanikhola Rural Municipality', 'खानीखोला गाउँपालिका'),
(359, 31001, 'Bagmati', 'Ramechhap', 'Umakunda Rural Municipality', 'उमाकुण्ड गाउँपालिका'),
(360, 31002, 'Bagmati', 'Ramechhap', 'Gokulganga Rural Municipality', 'गोकुलगङ्गा गाउँपालिका'),
(361, 31003, 'Bagmati', 'Ramechhap', 'Likhu Tamakoshi Rural Municipality', 'लिखु तामाकोशी गाउँपालिका'),
(362, 31004, 'Bagmati', 'Ramechhap', 'Ramechhap Urban Municipality', 'रामेछाप नगरपालिका'),
(363, 31005, 'Bagmati', 'Ramechhap', 'Manthali  Urban Municipality', 'मन्थली नगरपालिका'),
(364, 31006, 'Bagmati', 'Ramechhap', 'Khandadevi Rural Municipality', 'खाँडादेवी गाउँपालिका'),
(365, 31007, 'Bagmati', 'Ramechhap', 'Doramba Rural Municipality', 'दोरम्बा गाउँपालिका'),
(366, 31008, 'Bagmati', 'Ramechhap', 'Sunapati Rural Municipality', 'सुनापती गाउँपालिका'),
(367, 31101, 'Bagmati', 'Sindhuli', 'Dudhouli Urban Municipality', 'दुधौली नगरपालिका'),
(368, 31102, 'Bagmati', 'Sindhuli', 'Phikkal Rural Municipality', 'फिक्कल गाउँपालिका'),
(369, 31103, 'Bagmati', 'Sindhuli', 'Tinpatan Rural Municipality', 'तीनपाटन गाउँपालिका'),
(370, 31104, 'Bagmati', 'Sindhuli', 'Golanjor Rural Municipality', 'गोलन्जोर गाउँपालिका'),
(371, 31105, 'Bagmati', 'Sindhuli', 'Kamalamai Urban Municipality', 'कमलामाई नगरपालिका'),
(372, 31106, 'Bagmati', 'Sindhuli', 'Sunkoshi Rural Municipality', 'सुनकोशी गाउँपालिका'),
(373, 31107, 'Bagmati', 'Sindhuli', 'Ghyanglekha Rural Municipality', 'ध्याङलेख गाउँपालिका'),
(374, 31108, 'Bagmati', 'Sindhuli', 'Marin Rural Municipality', 'मरिण गाउँपालिका'),
(375, 31109, 'Bagmati', 'Sindhuli', 'Hariharpurgaghi Rural Municipality', 'हरिहरपुरगढी गाउँपालिका'),
(376, 31201, 'Bagmati', 'Makwanpur', 'Indrasarowar Rural Municipality', 'ईन्द्रसरोवर गाउँपालिका'),
(377, 31202, 'Bagmati', 'Makwanpur', 'Thaha Urban Municipality', 'थाहा नगरपालिका'),
(378, 31203, 'Bagmati', 'Makwanpur', 'Kailash Rural Municipality', 'कैलाश गाउँपालिका'),
(379, 31204, 'Bagmati', 'Makwanpur', 'Raksirang Rural Municipality', 'राक्सिराङ्ग गाउँपालिका'),
(380, 31205, 'Bagmati', 'Makwanpur', 'Manahari Rural Municipality', 'मनहरी गाउँपालिका'),
(381, 31206, 'Bagmati', 'Makwanpur', 'Hetauda Sub-Metropolitian City', 'हेटौडा उपमहानगरपालिका'),
(382, 31207, 'Bagmati', 'Makwanpur', 'Bhimphedi Rural Municipality', 'भिमफेदी गाउँपालिका'),
(383, 31208, 'Bagmati', 'Makwanpur', 'Makawanpurgadhi Rural Municipality', 'मकवानपुरगढी गाउँपालिका'),
(384, 31209, 'Bagmati', 'Makwanpur', 'Bakaiya Rural Municipality', 'बकैया गाउँपालिका'),
(385, 31210, 'Bagmati', 'Makwanpur', 'Bagmati Rural Municipality', 'बाग्मती गाउँपालिका'),
(386, 31301, 'Bagmati', 'Chitawan', 'Rapti Urban Municipality', 'राप्ती नगरपालिका'),
(387, 31302, 'Bagmati', 'Chitawan', 'Kalika Urban Municipality', 'कालिका नगरपालिका'),
(388, 31303, 'Bagmati', 'Chitawan', 'Ichchha Kamana Rural Municipality', 'इच्छाकामना गाउँपालिका'),
(389, 31304, 'Bagmati', 'Chitawan', 'Bharatpur Metropolitian City', 'भरतपुर महानगरपालिका'),
(390, 31305, 'Bagmati', 'Chitawan', 'Ratnanagar Urban Municipality', 'रत्ननगर नगरपालिका'),
(391, 31306, 'Bagmati', 'Chitawan', 'Khairahani Urban Municipality', 'खैरहनी नगरपालिका'),
(392, 31307, 'Bagmati', 'Chitawan', 'Madi Urban Municipality', 'मादी नगरपालिका'),
(393, 40101, 'Gandaki', 'Gorkha', 'Chumanubri Rural Municipality', 'चुमनुब्री गाउँपालिका'),
(394, 40102, 'Gandaki', 'Gorkha', 'Ajirkot Rural Municipality', 'अजिरकोट गाउँपालिका'),
(395, 40103, 'Gandaki', 'Gorkha', 'Barpak Sulikot Rural Municipality', 'बारपाक सुलिकोट गाउँपालिका'),
(396, 40104, 'Gandaki', 'Gorkha', 'Dharche Rural Municipality', 'धार्चे गाउँपालिका'),
(397, 40105, 'Gandaki', 'Gorkha', 'Aarughat Rural Municipality', 'आरुघाट गाउँपालिका'),
(398, 40106, 'Gandaki', 'Gorkha', 'Bhimsenthapa Rural Municipality', 'भिमसेनथापा गाउँपालिका'),
(399, 40107, 'Gandaki', 'Gorkha', 'Siranchowk Rural Municipality', 'सिरानचोक गाउँपालिका'),
(400, 40108, 'Gandaki', 'Gorkha', 'Palungtar Urban Municipality', 'पालुङ्गटार नगरपालिका'),
(401, 40109, 'Gandaki', 'Gorkha', 'Gorkha Urban Municipality', 'गोरखा नगरपालिका'),
(402, 40110, 'Gandaki', 'Gorkha', 'Shahid Lakhan Rural Municipality', 'शहीद लखन गाउँपालिका'),
(403, 40111, 'Gandaki', 'Gorkha', 'Gandaki Rural Municipality', 'गण्डकी गाउँपालिका'),
(404, 40201, 'Gandaki', 'Manang', 'Narpa Bhumi Rural Municipality', 'नार्पा भूमि गाउँपालिका'),
(405, 40202, 'Gandaki', 'Manang', 'Manang Ngisyang Rural Municipality', 'मनाङ ङिस्याङ गाउँपालिका'),
(406, 40203, 'Gandaki', 'Manang', 'Chame Rural Municipality', 'चामे गाउँपालिका'),
(407, 40204, 'Gandaki', 'Manang', 'Nason Rural Municipality', 'नासोँ गाउँपालिका'),
(408, 40301, 'Gandaki', 'Mustang', 'Lo Ghekar Damodarkunda Rural Municipality', 'लो-घेकर दामोदरकुण्ड गाउँपालिका'),
(409, 40302, 'Gandaki', 'Mustang', 'Gharpajhong Rural Municipality', 'घरपझोङ गाउँपालिका'),
(410, 40303, 'Gandaki', 'Mustang', 'Varagung Muktichhetra Rural Municipality', 'वारागुङ मुक्तिक्षेत्र गाउँपालिका'),
(411, 40304, 'Gandaki', 'Mustang', 'Lomanthang Rural Municipality', 'लोमन्थाङ गाउँपालिका'),
(412, 40305, 'Gandaki', 'Mustang', 'Thasang Rural Municipality', 'थासाङ गाउँपालिका'),
(413, 40401, 'Gandaki', 'Myagdi', 'Annapurna Rural Municipality', 'अन्नपूर्ण गाउँपालिका'),
(414, 40402, 'Gandaki', 'Myagdi', 'Raghuganga Rural Municipality', 'रघुगंगा गाउँपालिका'),
(415, 40403, 'Gandaki', 'Myagdi', 'Dhawalagiri Rural Municipality', 'धवलागिरी गाउँपालिका'),
(416, 40404, 'Gandaki', 'Myagdi', 'Malika Rural Municipality', 'मालिका गाउँपालिका'),
(417, 40405, 'Gandaki', 'Myagdi', 'Mangala Rural Municipality', 'मंगला गाउँपालिका'),
(418, 40406, 'Gandaki', 'Myagdi', 'Beni Urban Municipality', 'बेनी नगरपालिका'),
(419, 40501, 'Gandaki', 'Kaski', 'Madi Rural Municipality', 'मादी गाउँपालिका'),
(420, 40502, 'Gandaki', 'Kaski', 'Machhapuchchhre Rural Municipality', 'माछापुच्छ्र्े गाउँपालिका'),
(421, 40503, 'Gandaki', 'Kaski', 'Annapurna Rural Municipality', 'अन्नपूर्ण गाउँपालिका'),
(422, 40504, 'Gandaki', 'Kaski', 'Pokhara Metropolitian City', 'पोखरा महानगरपालिका'),
(423, 40505, 'Gandaki', 'Kaski', 'Rupa Rural Municipality', 'रूपा गाउँपालिका'),
(424, 40601, 'Gandaki', 'Lamjung', 'Dordi Rural Municipality', 'दोर्दी गाउँपालिका'),
(425, 40602, 'Gandaki', 'Lamjung', 'Marshyangdi Rural Municipality', 'मस्र्याङ्गदी गाउँपालिका'),
(426, 40603, 'Gandaki', 'Lamjung', 'Kwhola Sothar Rural Municipality', 'क्ब्होलासोथार गाउँपालिका'),
(427, 40604, 'Gandaki', 'Lamjung', 'Madhya Nepal Urban Municipality', 'मध्यनेपाल नगरपालिका'),
(428, 40605, 'Gandaki', 'Lamjung', 'Bensi Shahar Urban Municipality', 'बेंसीशहर नगरापालिका'),
(429, 40606, 'Gandaki', 'Lamjung', 'Sundarbazar Urban Municipality', 'सुन्दरबजार नगरपालिका'),
(430, 40607, 'Gandaki', 'Lamjung', 'Rainas Urban Municipality', 'राईनास नगरपालिका'),
(431, 40608, 'Gandaki', 'Lamjung', 'Dudhapokhari Rural Municipality', 'दुधपोखरी गाउँपालिका'),
(432, 40701, 'Gandaki', 'Tanahu', 'Bhanu Urban Municipality', 'भानु नगरपालिका'),
(433, 40702, 'Gandaki', 'Tanahu', 'Byas Urban Municipality', 'ब्यास नगरपालिका'),
(434, 40703, 'Gandaki', 'Tanahu', 'Myagde Rural Municipality', 'म्याग्दे गाउँपालिका'),
(435, 40704, 'Gandaki', 'Tanahu', 'Shuklagandaki Urban Municipality', 'शुक्लागण्डकी नगरपालिका'),
(436, 40705, 'Gandaki', 'Tanahu', 'Bhimad Urban Municipality', 'भिमाद नगरपालिका'),
(437, 40706, 'Gandaki', 'Tanahu', 'Ghiring Rural Municipality', 'घिरिङ्ग गाउँपालिका'),
(438, 40707, 'Gandaki', 'Tanahu', 'Rhishing Rural Municipality', 'ऋषिङ्ग गाउँपालिका'),
(439, 40708, 'Gandaki', 'Tanahu', 'Devghat Rural Municipality', 'देवघाट गाउँपालिका'),
(440, 40709, 'Gandaki', 'Tanahu', 'Bandipur Rural Municipality', 'बन्दिपुर गाउँपालिका'),
(441, 40710, 'Gandaki', 'Tanahu', 'Aanbu Khaireni Rural Municipality', 'आँबुखैरेनी गाउँपालिका'),
(442, 40801, 'Gandaki', 'Nawalparasi (East)', 'Gaidakot Urban Municipality', 'गैडाकोट नगरपालिका'),
(443, 40802, 'Gandaki', 'Nawalparasi (East)', 'Bulingtar Rural Municipality', 'बुलिङ्गटार गाउँपालिका'),
(444, 40803, 'Gandaki', 'Nawalparasi (East)', 'Baudikali Rural Municipality', 'बौदीकाली गाउँपालिका'),
(445, 40804, 'Gandaki', 'Nawalparasi (East)', 'Hupsekot Rural Municipality', 'हुप्सेकोट गाउँपालिका'),
(446, 40805, 'Gandaki', 'Nawalparasi (East)', 'Devchuli Urban Municipality', 'देवचुली नगरपालिका'),
(447, 40806, 'Gandaki', 'Nawalparasi (East)', 'Kawasoti Urban Municipality', 'कावासोती नगरपालिका'),
(448, 40807, 'Gandaki', 'Nawalparasi (East)', 'Madhya Bindu Urban Municipality', 'मध्यबिन्दु नगरपालिका'),
(449, 40808, 'Gandaki', 'Nawalparasi (East)', 'Binayi Tribeni Rural Municipality', 'बिनयी त्रिवेणी गाउँपालिका'),
(450, 40901, 'Gandaki', 'Syangja', 'Putalibazar Urban Municipality', 'पुतलीबजार नगरपालिका'),
(451, 40902, 'Gandaki', 'Syangja', 'Phedikhola Rural Municipality', 'फेदीखोला गाउँपालिका'),
(452, 40903, 'Gandaki', 'Syangja', 'Aandhikhola Rural Municipality', 'आँधिखोला गाउँपालिका'),
(453, 40904, 'Gandaki', 'Syangja', 'Arjun Choupari Rural Municipality', 'अर्जुनचौपारी गाउँपालिका'),
(454, 40905, 'Gandaki', 'Syangja', 'Bhirkot Urban Municipality', 'भीरकोट नगरपालिका'),
(455, 40906, 'Gandaki', 'Syangja', 'Biruwa Rural Municipality', 'बिरुवा गाउँपालिका'),
(456, 40907, 'Gandaki', 'Syangja', 'Harinas Rural Municipality', 'हरिनास गाउँपालिका'),
(457, 40908, 'Gandaki', 'Syangja', 'Chapakot Urban Municipality', 'चापाकोट नगरपालिका'),
(458, 40909, 'Gandaki', 'Syangja', 'Walling Urban Municipality', 'वालिङ्ग नगरपालिका'),
(459, 40910, 'Gandaki', 'Syangja', 'Galyang Urban Municipality', 'गल्याङ नगरपालिका'),
(460, 40911, 'Gandaki', 'Syangja', 'Kaligandaki Rural Municipality', 'कालीगण्डकी गाउँपालिका'),
(461, 41001, 'Gandaki', 'Parbat', 'Modi Rural Municipality', 'मोदी गाउँपालिका'),
(462, 41002, 'Gandaki', 'Parbat', 'Jaljala Rural Municipality', 'जलजला गाउँपालिका'),
(463, 41003, 'Gandaki', 'Parbat', 'Kushma Urban Municipality', 'कुश्मा नगरपालिका'),
(464, 41004, 'Gandaki', 'Parbat', 'Phalebas Urban Municipality', 'फलेबास नगरपालिका'),
(465, 41005, 'Gandaki', 'Parbat', 'Mahashila Rural Municipality', 'महाशिला गाउँपालिका'),
(466, 41006, 'Gandaki', 'Parbat', 'Bihadi Rural Municipality', 'बिहादी गाउँपालिका'),
(467, 41007, 'Gandaki', 'Parbat', 'Paiyu Rural Municipality', 'पैयुं गाउँपालिका'),
(468, 41101, 'Gandaki', 'Baglung', 'Baglung Urban Municipality', 'बाग्लुङ्ग नगरपालिका'),
(469, 41102, 'Gandaki', 'Baglung', 'Kathekhola Rural Municipality', 'काठेखोला गाउँपालिका'),
(470, 41103, 'Gandaki', 'Baglung', 'Tarakhola Rural Municipality', 'ताराखोला गाउँपालिका'),
(471, 41104, 'Gandaki', 'Baglung', 'Tamankhola Rural Municipality', 'तमानखोला गाउँपालिका'),
(472, 41105, 'Gandaki', 'Baglung', 'Dhorpatan Urban Municipality', 'ढोरपाटन नगरपालिका'),
(473, 41106, 'Gandaki', 'Baglung', 'Nisikhola Rural Municipality', 'निसीखोला गाउँपालिका'),
(474, 41107, 'Gandaki', 'Baglung', 'Badigad Rural Municipality', 'बडिगाड गाउँपालिका'),
(475, 41108, 'Gandaki', 'Baglung', 'Galkot Urban Municipality', 'गल्कोट नगरपालिका'),
(476, 41109, 'Gandaki', 'Baglung', 'Bareng Rural Municipality', 'बरेङ गाउँपालिका'),
(477, 41110, 'Gandaki', 'Baglung', 'Jaimuni Urban Municipality', 'जैमुनी नगरपालिका'),
(478, 50101, 'Lumbini', 'Rukum (East)', 'Putha Uttanganga Rural Municipality', 'पुथा उत्तरगंगा गाउँपालिका'),
(479, 50102, 'Lumbini', 'Rukum (East)', 'Sisne Rural Municipality', 'सिस्ने गाउँपालिका'),
(480, 50103, 'Lumbini', 'Rukum (East)', 'Bhoome Rural Municipality', 'भूमे गाउँपालिका'),
(481, 50201, 'Lumbini', 'Rolpa', 'Sunchhahari Rural Municipality', 'सुनछहरी गाउँपालिका'),
(482, 50202, 'Lumbini', 'Rolpa', 'Thawang Rural Municipality', 'थबाङ्ग गाउँपालिका'),
(483, 50203, 'Lumbini', 'Rolpa', 'Pariwartan Rural Municipality', 'परिवर्तन गाउँपालिका'),
(484, 50204, 'Lumbini', 'Rolpa', 'Gangadev Rural Municipality', 'गंगादेव गाउँपालिका'),
(485, 50205, 'Lumbini', 'Rolpa', 'Madi Rural Municipality', 'मादी गाउँपालिका'),
(486, 50206, 'Lumbini', 'Rolpa', 'Tribeni Rural Municipality', 'त्रिवेणी गाउँपालिका'),
(487, 50207, 'Lumbini', 'Rolpa', 'Rolpa Urban Municipality', 'रोल्पा नगरपालिका'),
(488, 50208, 'Lumbini', 'Rolpa', 'Runtigadhi Rural Municipality', 'रुन्टीगढी गाउँपालिका'),
(489, 50209, 'Lumbini', 'Rolpa', 'Sunil Smriti Rural Municipality', 'सुनिल स्मृति गाउँपालिका'),
(490, 50210, 'Lumbini', 'Rolpa', 'Lungri Rural Municipality', 'लुङ्ग्री गाउँपालिका'),
(491, 50301, 'Lumbini', 'Pyuthan', 'Gaumukhi Rural Municipality', 'गौमुखी गाउँपालिका'),
(492, 50302, 'Lumbini', 'Pyuthan', 'Naubahini Rural Municipality', 'नौबहिनी गाउँपालिका'),
(493, 50303, 'Lumbini', 'Pyuthan', 'Jhimaruk Rural Municipality', 'झिमरुक गाउँपालिका'),
(494, 50304, 'Lumbini', 'Pyuthan', 'Pyuthan Urban Municipality', 'प्यूठान नगरपालिका'),
(495, 50305, 'Lumbini', 'Pyuthan', 'Sworgadwari Urban Municipality', 'स्वर्गद्धारी नगरपालिका'),
(496, 50306, 'Lumbini', 'Pyuthan', 'Mandavi Rural Municipality', 'माण्डवी गाउँपालिका'),
(497, 50307, 'Lumbini', 'Pyuthan', 'Mallarani Rural Municipality', 'मल्लरानी गाउँपालिका'),
(498, 50308, 'Lumbini', 'Pyuthan', 'Aairawati Rural Municipality', 'ऐरावती गाउँपालिका'),
(499, 50309, 'Lumbini', 'Pyuthan', 'Sarumarani Rural Municipality', 'सरुमारानी गाउँपालिका'),
(500, 50401, 'Lumbini', 'Gulmi', 'Kali Gandaki Rural Municipality', 'कालिगण्डकी गाउँपालिका'),
(501, 50402, 'Lumbini', 'Gulmi', 'Satyawoti Rural Municipality', 'सत्यवती गाउँपालिका'),
(502, 50403, 'Lumbini', 'Gulmi', 'Chandrakot Rural Municipality', 'चन्द्रकोट गाउँपालिका'),
(503, 50404, 'Lumbini', 'Gulmi', 'Musikot Urban Municipality', 'मुसिकोट नगरपालिका'),
(504, 50405, 'Lumbini', 'Gulmi', 'Isma Rural Municipality', 'ईस्मा गाउँपालिका'),
(505, 50406, 'Lumbini', 'Gulmi', 'Malika Rural Municipality', 'मालिका गाउँपालिका'),
(506, 50407, 'Lumbini', 'Gulmi', 'Madane Rural Municipality', 'मदाने गाउँपालिका'),
(507, 50408, 'Lumbini', 'Gulmi', 'Dhurkot Rural Municipality', 'धुर्कोट गाउँपालिका'),
(508, 50409, 'Lumbini', 'Gulmi', 'Resunga Urban Municipality', 'रेसुङ्गा नगरपालिका'),
(509, 50410, 'Lumbini', 'Gulmi', 'Gulmi Durbar Rural Municipality', 'गुल्मी दरबार गाउँपालिका'),
(510, 50411, 'Lumbini', 'Gulmi', 'Chhatrakot Rural Municipality', 'छत्रकोट गाउँपालिका'),
(511, 50412, 'Lumbini', 'Gulmi', 'Ruruchhetra Rural Municipality', 'रुरुक्षेत्र गाउँपालिका'),
(512, 50501, 'Lumbini', 'Arghakhanchi', 'Chhatradev Rural Municipality', 'छत्रदेव गाउँपालिका'),
(513, 50502, 'Lumbini', 'Arghakhanchi', 'Malarani Rural Municipality', 'मालारानी गाउँपालिका'),
(514, 50503, 'Lumbini', 'Arghakhanchi', 'Bhumikasthan Urban Municipality', 'भुमिकास्थान नगरपालिका'),
(515, 50504, 'Lumbini', 'Arghakhanchi', 'Sandhikharka Urban Municipality', 'सन्धिखर्क नगरपालिका'),
(516, 50505, 'Lumbini', 'Arghakhanchi', 'Panini Rural Municipality', 'पाणिनी गाउँपालिका'),
(517, 50506, 'Lumbini', 'Arghakhanchi', 'Shitaganga Urban Municipality', 'शितगंगा नगरपालिका'),
(518, 50601, 'Lumbini', 'Palpa', 'Rampur Urban Municipality', 'रामपुर नगरपालिका'),
(519, 50602, 'Lumbini', 'Palpa', 'Purbakhola Rural Municipality', 'पुर्वखोला गाउँपालिका'),
(520, 50603, 'Lumbini', 'Palpa', 'Rambha Rural Municipality', 'रम्भा गाउँपालिका'),
(521, 50604, 'Lumbini', 'Palpa', 'Baganaskali Rural Municipality', 'बगनासकाली गाउँपालिका'),
(522, 50605, 'Lumbini', 'Palpa', 'Tansen Urban Municipality', 'तानसेन नगरपालिका'),
(523, 50606, 'Lumbini', 'Palpa', 'Ribdikot Rural Municipality', 'रिब्दीकोट गाउँपालिका'),
(524, 50607, 'Lumbini', 'Palpa', 'Rainadevi Chhahara Rural Municipality', 'रैनादेवी छहरा गाउँपालिका'),
(525, 50608, 'Lumbini', 'Palpa', 'Tinau Rural Municipality', 'तिनाउ गाउँपालिका'),
(526, 50609, 'Lumbini', 'Palpa', 'Mathagadhi Rural Municipality', 'माथागढी गाउँपालिका'),
(527, 50610, 'Lumbini', 'Palpa', 'Nisdi Rural Municipality', 'निस्दी गाउँपालिका'),
(528, 50701, 'Lumbini', 'Nawalparasi (West)', 'Bardaghat Urban Municipality', 'बर्दघाट नगरपालिका'),
(529, 50702, 'Lumbini', 'Nawalparasi (West)', 'Sunawal Urban Municipality', 'सुनवल नगरपालिका'),
(530, 50703, 'Lumbini', 'Nawalparasi (West)', 'Ramgram Urban Municipality', 'रामग्राम नगरपालिका'),
(531, 50704, 'Lumbini', 'Nawalparasi (West)', 'Palhinandan Rural Municipality', 'पाल्हीनन्दन गाउँपालिका'),
(532, 50705, 'Lumbini', 'Nawalparasi (West)', 'Sarawal Rural Municipality', 'सरावल गाउँपालिका'),
(533, 50706, 'Lumbini', 'Nawalparasi (West)', 'Pratapapur Rural Municipality', 'प्रतापपुर गाउँपालिका'),
(534, 50707, 'Lumbini', 'Nawalparasi (West)', 'Susta Rural Municipality', 'सुस्ता गाउँपालिका'),
(535, 50801, 'Lumbini', 'Rupandehi', 'Devdaha Urban Municipality', 'देबदह नगरपालिका'),
(536, 50802, 'Lumbini', 'Rupandehi', 'Butwal Sub-Metropolitian City', 'बुटवल उपमहानगरपालिका'),
(537, 50803, 'Lumbini', 'Rupandehi', 'Sainamaina Urban Municipality', 'सैनामैना नगरपालिका'),
(538, 50804, 'Lumbini', 'Rupandehi', 'Kanchan Rural Municipality', 'कञ्चन गाउँपालिका'),
(539, 50805, 'Lumbini', 'Rupandehi', 'Gaidahawa Rural Municipality', 'गैडहवा गाउँपालिका'),
(540, 50806, 'Lumbini', 'Rupandehi', 'Suddhodhan Rural Municipality', 'सुद्धोधन गाउँपालिका'),
(541, 50807, 'Lumbini', 'Rupandehi', 'Siyari Rural Municipality', 'सियारी गाउँपालिका'),
(542, 50808, 'Lumbini', 'Rupandehi', 'Tilottama Urban Municipality', 'तिलोत्तमा नगरापालिका'),
(543, 50809, 'Lumbini', 'Rupandehi', 'Om Satiya Rural Municipality', 'ओमसतिया गाउँपालिका'),
(544, 50810, 'Lumbini', 'Rupandehi', 'Rohini Rural Municipality', 'रोहिणी गाउँपालिका'),
(545, 50811, 'Lumbini', 'Rupandehi', 'Siddharthanagar Urban Municipality', 'सिद्धार्थनगर नगरपालिका'),
(546, 50812, 'Lumbini', 'Rupandehi', 'Mayadevi Rural Municipality', 'मायादेवी गाउँपालिका'),
(547, 50813, 'Lumbini', 'Rupandehi', 'Lumbini Sanskritik Urban Municipality', 'लुम्बिनी साँस्कृतिक नगरपालिका'),
(548, 50814, 'Lumbini', 'Rupandehi', 'Kotahimai Rural Municipality', 'कोटहीमाई गाउँपालिका'),
(549, 50815, 'Lumbini', 'Rupandehi', 'Sammarimai Rural Municipality', 'सम्मरीमाई गाउँपालिका'),
(550, 50816, 'Lumbini', 'Rupandehi', 'Marchawari Rural Municipality', 'मर्चवारी गाउँपालिका'),
(551, 50901, 'Lumbini', 'Kapilbastu', 'Banganga Urban Municipality', 'बाणगंगा नगरपालिका'),
(552, 50902, 'Lumbini', 'Kapilbastu', 'Buddhabhumi Urban Municipality', 'बुद्धभूमी नगरपालिका'),
(553, 50903, 'Lumbini', 'Kapilbastu', 'Shivaraj Urban Municipality', 'शिवराज नगरपालिका'),
(554, 50904, 'Lumbini', 'Kapilbastu', 'Bijayanagar Rural Municipality', 'बिजयनगर गाउँपालिका'),
(555, 50905, 'Lumbini', 'Kapilbastu', 'Krishnanagar Urban Municipality', 'कृष्णनगर नगरपालिका'),
(556, 50906, 'Lumbini', 'Kapilbastu', 'Maharajganj Urban Municipality', 'महाराजगन्ज नगरपालिका'),
(557, 50907, 'Lumbini', 'Kapilbastu', 'Kapilbastu Urban Municipality', 'कपिलबस्तु नगरपालिका'),
(558, 50908, 'Lumbini', 'Kapilbastu', 'Yasodhara Rural Municipality', 'यसोधरा गाउँपालिका');
INSERT INTO `PALIKA` (`P_ID`, `P_CODE`, `PROVIENCE`, `DISTRICT`, `LOCAL_GOV_EN`, `LOCAL_GOV_NP`) VALUES
(559, 50909, 'Lumbini', 'Kapilbastu', 'Mayadevi Rural Municipality', 'मायादेवी गाउँपालिका'),
(560, 50910, 'Lumbini', 'Kapilbastu', 'Shuddhodhan Rural Municipality', 'शुद्धोधन गाउँपालिका'),
(561, 51001, 'Lumbini', 'Dang', 'Bangalachuli Rural Municipality', 'बंगलाचुली गाउँपालिका'),
(562, 51002, 'Lumbini', 'Dang', 'Ghorahi Sub-Metropolitian City', 'घोराही उपमहानगरपालिका'),
(563, 51003, 'Lumbini', 'Dang', 'Tulsipur Sub-Metropolitian City', 'तुल्सीपुर उपमहानगरपालिका'),
(564, 51004, 'Lumbini', 'Dang', 'Shantinagar Rural Municipality', 'शान्तिनगर गाउँपालिका'),
(565, 51005, 'Lumbini', 'Dang', 'Babai Rural Municipality', 'बबई गाउँपालिका'),
(566, 51006, 'Lumbini', 'Dang', 'Dangisharan Rural Municipality', 'दंगीशरण गाउँपालिका'),
(567, 51007, 'Lumbini', 'Dang', 'Lamahi Urban Municipality', 'लमही नगरपालिका'),
(568, 51008, 'Lumbini', 'Dang', 'Rapti Rural Municipality', 'राप्ती गाउँपालिका'),
(569, 51009, 'Lumbini', 'Dang', 'Gadhawa Rural Municipality', 'गढवा गाउँपालिका'),
(570, 51010, 'Lumbini', 'Dang', 'Rajpur Rural Municipality', 'राजपुर गाउँपालिका'),
(571, 51101, 'Lumbini', 'Banke', 'Rapti Sonari Rural Municipality', 'राप्ती सोनारी गाउँपालिका'),
(572, 51102, 'Lumbini', 'Banke', 'Kohalpur Urban Municipality', 'कोहलपुर नगरपालिका'),
(573, 51103, 'Lumbini', 'Banke', 'Baijanath Rural Municipality', 'बैजनाथ गाउँपालिका'),
(574, 51104, 'Lumbini', 'Banke', 'Khajura Rural Municipality', 'खजुरा गाउँपालिका'),
(575, 51105, 'Lumbini', 'Banke', 'Janaki Rural Municipality', 'जानकी गाउँपालिका'),
(576, 51106, 'Lumbini', 'Banke', 'Nepalganj Sub-Metropolitian City', 'नेपालगञ्ज उपमहानगरपालिका'),
(577, 51107, 'Lumbini', 'Banke', 'Duduwa Rural Municipality', 'डुडुवा गाउँपालिका'),
(578, 51108, 'Lumbini', 'Banke', 'Narainapur Rural Municipality', 'नरैनापुर गाउँपालिका'),
(579, 51201, 'Lumbini', 'Bardiya', 'Bansgadhi Urban Municipality', 'बाँसगढी नगरपालिका'),
(580, 51202, 'Lumbini', 'Bardiya', 'Barbardiya Urban Municipality', 'बारबर्दिया नगरपालिका'),
(581, 51203, 'Lumbini', 'Bardiya', 'Thakurbaba Urban Municipality', 'ठाकुरबाबा नगरपालिका'),
(582, 51204, 'Lumbini', 'Bardiya', 'Geruwa Rural Municipality', 'गेरुवा गाउँपालिका'),
(583, 51205, 'Lumbini', 'Bardiya', 'Rajapur Urban Municipality', 'राजापुर नगरपालिका'),
(584, 51206, 'Lumbini', 'Bardiya', 'Madhuwan Urban Municipality', 'मधुवन नगरपालिका'),
(585, 51207, 'Lumbini', 'Bardiya', 'Gulariya Urban Municipality', 'गुलरीया नगरपालिका'),
(586, 51208, 'Lumbini', 'Bardiya', 'Badhaiyatal Rural Municipality', 'बढैयाताल गाउँपालिका'),
(587, 60101, 'Karnali', 'Dolpa', 'Dolpo Buddha Rural Municipality', 'डोल्पो बुद्ध गाउँपालिका'),
(588, 60102, 'Karnali', 'Dolpa', 'Shey Phoksundo Rural Municipality', 'शे फोक्सुण्डो गाउँपालिका'),
(589, 60103, 'Karnali', 'Dolpa', 'Jagadulla Rural Municipality', 'जगदुल्ला गाउँपालिका'),
(590, 60104, 'Karnali', 'Dolpa', 'Mudkechula Rural Municipality', 'मुड्केचुला गाउँपालिका'),
(591, 60105, 'Karnali', 'Dolpa', 'Tripurasundari Urban Municipality', 'त्रिपुरासुन्दरी नगरपालिका'),
(592, 60106, 'Karnali', 'Dolpa', 'Thulibheri Urban Municipality', 'ठुलीभेरी नगरपालिका'),
(593, 60107, 'Karnali', 'Dolpa', 'Kaike Rural Municipality', 'काइके गाउँपालिका'),
(594, 60108, 'Karnali', 'Dolpa', 'Chharka Tangsong Rural Municipality', 'छार्का ताङसोङ गाउँपालिका'),
(595, 60201, 'Karnali', 'Mugu', 'Mugumakarmarog Rural Municipality', 'मुगुमकार्मारोग गाउँपालिका'),
(596, 60202, 'Karnali', 'Mugu', 'Chhayanath Rara Urban Municipality', 'छायाँनाथ रारा नगरपालिका'),
(597, 60203, 'Karnali', 'Mugu', 'Soru Rural Municipality', 'सोरु गाउँपालिका'),
(598, 60204, 'Karnali', 'Mugu', 'Khatyad Rural Municipality', 'खत्याड गाउँपालिका'),
(599, 60301, 'Karnali', 'Humla', 'Chankheli Rural Municipality', 'चंखेली गाउँपालिका'),
(600, 60302, 'Karnali', 'Humla', 'Kharpunath Rural Municipality', 'खार्पुनाथ गाउँपालिका'),
(601, 60303, 'Karnali', 'Humla', 'Simkot Rural Municipality', 'सिमकोट गाउँपालिका'),
(602, 60304, 'Karnali', 'Humla', 'Namkha Rural Municipality', 'नाम्खा गाउँपालिका'),
(603, 60305, 'Karnali', 'Humla', 'Sarkegad Rural Municipality', 'सर्केगाड गाउँपालिका'),
(604, 60306, 'Karnali', 'Humla', 'Adanchuli Rural Municipality', 'अदानचुली गाउँपालिका'),
(605, 60307, 'Karnali', 'Humla', 'Tanjakot Rural Municipality', 'ताँजाकोट गाउँपालिका'),
(606, 60401, 'Karnali', 'Jumla', 'Patarasi Rural Municipality', 'पातारासी गाउँपालिका'),
(607, 60402, 'Karnali', 'Jumla', 'Kanaka Sundari Rural Municipality', 'कनका सुन्दरी गाउँपालिका'),
(608, 60403, 'Karnali', 'Jumla', 'Sinja Rural Municipality', 'सिंजा गाउँपालिका'),
(609, 60404, 'Karnali', 'Jumla', 'Chandannath Urban Municipality', 'चन्दननाथ नगरपालिका'),
(610, 60405, 'Karnali', 'Jumla', 'Guthichaur Rural Municipality', 'गुठिचौर गाउँपालिका'),
(611, 60406, 'Karnali', 'Jumla', 'Tatopani Rural Municipality', 'तातोपानी गाउँपालिका'),
(612, 60407, 'Karnali', 'Jumla', 'Tila Rural Municipality', 'तिला गाउँपालिका'),
(613, 60408, 'Karnali', 'Jumla', 'Hima Rural Municipality', 'हिमा गाउँपालिका'),
(614, 60501, 'Karnali', 'Kalikot', 'Palata Rural Municipality', 'पलाता गाउँपालिका'),
(615, 60502, 'Karnali', 'Kalikot', 'Pachal Jharana Rural Municipality', 'पचाल झरना गाउँपालिका'),
(616, 60503, 'Karnali', 'Kalikot', 'Raskot Urban Municipality', 'रास्कोट नगरपालिका'),
(617, 60504, 'Karnali', 'Kalikot', 'Sanni Tribeni Rural Municipality', 'सान्नी त्रिवेणी गाउँपालिका'),
(618, 60505, 'Karnali', 'Kalikot', 'Naraharinath Rural Municipality', 'नरहरिनाथ गाउँपालिका'),
(619, 60506, 'Karnali', 'Kalikot', 'Khandachakra Urban Municipality', 'खाँडाचक्र नगरपालिका'),
(620, 60507, 'Karnali', 'Kalikot', 'Tilagupha Urban Municipality', 'तिलागुफा नगरपालिका'),
(621, 60508, 'Karnali', 'Kalikot', 'Mahawai Rural Municipality', 'महावै गाउँपालिका'),
(622, 60509, 'Karnali', 'Kalikot', 'Shuva Kalika Rural Municipality', 'शुभ कालीका गाउँपालिका'),
(623, 60601, 'Karnali', 'Dailekh', 'Naumule Rural Municipality', 'नौमुले गाउँपालिका'),
(624, 60602, 'Karnali', 'Dailekh', 'Mahabu Rural Municipality', 'महाबु गाउँपालिका'),
(625, 60603, 'Karnali', 'Dailekh', 'Bhairabi Rural Municipality', 'भैरवी गाउँपालिका'),
(626, 60604, 'Karnali', 'Dailekh', 'Thantikandh Rural Municipality', 'ठाँटीकाँध गाउँपालिका'),
(627, 60605, 'Karnali', 'Dailekh', 'Aathbis Urban Municipality', 'आठबीस नगरपालिका'),
(628, 60606, 'Karnali', 'Dailekh', 'Chamunda Bindrasaini Urban Municipality', 'चामुण्डा बिन्द्रासैनी नगरपालिका'),
(629, 60607, 'Karnali', 'Dailekh', 'Dullu Urban Municipality', 'दुल्लु नगरपालिका'),
(630, 60608, 'Karnali', 'Dailekh', 'Narayan Urban Municipality', 'नारायण नगरपालिका'),
(631, 60609, 'Karnali', 'Dailekh', 'Bhagawatimai Rural Municipality', 'भगवतीमाई गाउँपालिका'),
(632, 60610, 'Karnali', 'Dailekh', 'Dungeshwor Rural Municipality', 'डुङ्गेश्वर गाउँपालिका'),
(633, 60611, 'Karnali', 'Dailekh', 'Gurans Rural Municipality', 'गुराँस गाउँपालिका'),
(634, 60701, 'Karnali', 'Jajarkot', 'Barekot Rural Municipality', 'बारेकोट गाउँपालिका'),
(635, 60702, 'Karnali', 'Jajarkot', 'Kushe Rural Municipality', 'कुशे गाउँपालिका'),
(636, 60703, 'Karnali', 'Jajarkot', 'Junichande Rural Municipality', 'जुनीचाँदे गाउँपालिका'),
(637, 60704, 'Karnali', 'Jajarkot', 'Chhedagad Urban Municipality', 'छेडागाड नगरपालिका'),
(638, 60705, 'Karnali', 'Jajarkot', 'Shivalaya Rural Municipality', 'शिवालय गाउँपालिका'),
(639, 60706, 'Karnali', 'Jajarkot', 'Bheri Malika Urban Municipality', 'भेरीमालिका नगरपालिका'),
(640, 60707, 'Karnali', 'Jajarkot', 'Nalgad Urban Municipality', 'नलगाड नगरपालिका'),
(641, 60801, 'Karnali', 'Rukum (West)', 'Aathabisakot Urban Municipality', 'आठबिसकोट नगरपालिका'),
(642, 60802, 'Karnali', 'Rukum (West)', 'Sanibheri Rural Municipality', 'सानीभेरी गाउँपालिका'),
(643, 60803, 'Karnali', 'Rukum (West)', 'Banphikot Rural Municipality', 'बाँफिकोट गाउँपालिका'),
(644, 60804, 'Karnali', 'Rukum (West)', 'Musikot Urban Municipality', 'मुसिकोट नगरपालिका'),
(645, 60805, 'Karnali', 'Rukum (West)', 'Tribeni Rural Municipality', 'त्रिवेणी गाउँपालिका'),
(646, 60806, 'Karnali', 'Rukum (West)', 'Chaurjahari Urban Municipality', 'चौरजहारी नगरपालिका'),
(647, 60901, 'Karnali', 'Salyan', 'Darma Rural Municipality', 'दार्मा गाउँपालिका'),
(648, 60902, 'Karnali', 'Salyan', 'Kumakh Rural Municipality', 'कुमाख गाउँपालिका'),
(649, 60903, 'Karnali', 'Salyan', 'Banagad Kupinde Urban Municipality', 'बनगाड कुपिण्डे नगरपालिका'),
(650, 60904, 'Karnali', 'Salyan', 'Siddha Kumakh Rural Municipality', 'सिद्ध कुमाख गाउँपालिका'),
(651, 60905, 'Karnali', 'Salyan', 'Bagachour Urban Municipality', 'बागचौर नगरपालिका'),
(652, 60906, 'Karnali', 'Salyan', 'Chhatreshwori Rural Municipality', 'छत्रेश्वरी गाउँपालिका'),
(653, 60907, 'Karnali', 'Salyan', 'Sharada Urban Municipality', 'शारदा नगरपालिका'),
(654, 60908, 'Karnali', 'Salyan', 'Kalimati Rural Municipality', 'कालिमाटी गाउँपालिका'),
(655, 60909, 'Karnali', 'Salyan', 'Tribeni Rural Municipality', 'त्रिवेणी गाउँपालिका'),
(656, 60910, 'Karnali', 'Salyan', 'Kapurkot Rural Municipality', 'कपुरकोट गाउँपालिका'),
(657, 61001, 'Karnali', 'Surkhet', 'Simta Rural Municipality', 'सिम्ता गाउँपालिका'),
(658, 61002, 'Karnali', 'Surkhet', 'Chingad Rural Municipality', 'चिङ्गगाड गाउँपालिका'),
(659, 61003, 'Karnali', 'Surkhet', 'Lekabeshi Urban Municipality', 'लेकबेशी नगरपालिका'),
(660, 61004, 'Karnali', 'Surkhet', 'Gurbhakot Urban Municipality', 'गुर्भाकोट नगरपालिका'),
(661, 61005, 'Karnali', 'Surkhet', 'Bheriganga Urban Municipality', 'भेरीगंगा नगरपालिका'),
(662, 61006, 'Karnali', 'Surkhet', 'Birendranagar Urban Municipality', 'बीरेन्द्रनगर नगरपालिका'),
(663, 61007, 'Karnali', 'Surkhet', 'Barahatal Rural Municipality', 'बराहताल गाउँपालिका'),
(664, 61008, 'Karnali', 'Surkhet', 'Panchapuri Urban Municipality', 'पञ्चपुरी नगरपालिका'),
(665, 61009, 'Karnali', 'Surkhet', 'Chaukune Rural Municipality', 'चौकुने गाउँपालिका'),
(666, 70101, 'Sudur-Paschim', 'Bajura', 'Himali Rural Municipality', 'हिमाली गाउँपालिका'),
(667, 70102, 'Sudur-Paschim', 'Bajura', 'Gaumul Rural Municipality', 'गौमुल गाउँपालिका'),
(668, 70103, 'Sudur-Paschim', 'Bajura', 'Budhinanda Urban Municipality', 'बुढीनन्दा नगरपालिका'),
(669, 70104, 'Sudur-Paschim', 'Bajura', 'Swamikartik Khapar Rural Municipality', 'स्वामीकार्तिक खापर गाउँपालिका'),
(670, 70105, 'Sudur-Paschim', 'Bajura', 'Jagannath Rural Municipality', 'जगन्‍नाथ गाउँपालिका'),
(671, 70106, 'Sudur-Paschim', 'Bajura', 'Badimalika Urban Municipality', 'बडिमालिका नगरपालिका'),
(672, 70107, 'Sudur-Paschim', 'Bajura', 'Khaptad Chhededaha Rural Municipality', 'खप्तड छेडेदह गाउँपालिका'),
(673, 70108, 'Sudur-Paschim', 'Bajura', 'Budhiganga Urban Municipality', 'बुढीगंगा नगरपालिका'),
(674, 70109, 'Sudur-Paschim', 'Bajura', 'Tribeni Urban Municipality', 'त्रिवेणी नगरपालिका'),
(675, 70201, 'Sudur-Paschim', 'Bajhang', 'Saipal Rural Municipality', 'साइपाल गाउँपालिका'),
(676, 70202, 'Sudur-Paschim', 'Bajhang', 'Bungal Urban Municipality', 'बुंगल नगरपालिका'),
(677, 70203, 'Sudur-Paschim', 'Bajhang', 'Surma Rural Municipality', 'सूर्मा गाउँपालिका'),
(678, 70204, 'Sudur-Paschim', 'Bajhang', 'Talkot Rural Municipality', 'तालकोट गाउँपालिका'),
(679, 70205, 'Sudur-Paschim', 'Bajhang', 'Masta Rural Municipality', 'मष्टा गाउँपालिका'),
(680, 70206, 'Sudur-Paschim', 'Bajhang', 'Jayaprithbi Urban Municipality', 'जयपृथ्वी नगरपालिका'),
(681, 70207, 'Sudur-Paschim', 'Bajhang', 'Chhabis Pathibhara Rural Municipality', 'छबिस पाथिभरा गाउँपालिका'),
(682, 70208, 'Sudur-Paschim', 'Bajhang', 'Durgathali Rural Municipality', 'दुर्गाथली गाउँपालिका'),
(683, 70209, 'Sudur-Paschim', 'Bajhang', 'Kedarsyun Rural Municipality', 'केदारस्युँ गाउँपालिका'),
(684, 70210, 'Sudur-Paschim', 'Bajhang', 'Bitthadchir Rural Municipality', 'बित्थडचिर गाउँपालिका'),
(685, 70211, 'Sudur-Paschim', 'Bajhang', 'Thalara Rural Municipality', 'थलारा गाउँपालिका'),
(686, 70212, 'Sudur-Paschim', 'Bajhang', 'Khaptad Chhanna Rural Municipality', 'खप्तडछान्ना गाउँपालिका'),
(687, 70301, 'Sudur-Paschim', 'Darchula', 'Byas Rural Municipality', 'ब्याँस गाउँपालिका'),
(688, 70302, 'Sudur-Paschim', 'Darchula', 'Duhun Rural Municipality', 'दुहुँ गाउँपालिका'),
(689, 70303, 'Sudur-Paschim', 'Darchula', 'Mahakali Urban Municipality', 'महाकाली नगरपालिका'),
(690, 70304, 'Sudur-Paschim', 'Darchula', 'Naugad  Rural Municipality', 'नौगाड गाउँपालिका'),
(691, 70305, 'Sudur-Paschim', 'Darchula', 'Apihimal Rural Municipality', 'अपिहिमाल गाउँपालिका'),
(692, 70306, 'Sudur-Paschim', 'Darchula', 'Marma Rural Municipality', 'मार्मा गाउँपालिका'),
(693, 70307, 'Sudur-Paschim', 'Darchula', 'Shailyashikhar Urban Municipality', 'शैल्यशिखर नगरपालिका'),
(694, 70308, 'Sudur-Paschim', 'Darchula', 'Malikarjun Rural Municipality', 'मालिकार्जुन गाउँपालिका'),
(695, 70309, 'Sudur-Paschim', 'Darchula', 'Lekam Rural Municipality', 'लेकम गाउँपालिका'),
(696, 70401, 'Sudur-Paschim', 'Baitadi', 'Dilasaini Rural Municipality', 'डीलासैनी गाउँपालिका'),
(697, 70402, 'Sudur-Paschim', 'Baitadi', 'Dogada Kedar Rural Municipality', 'दोगडाकेदार गाउँपालिका'),
(698, 70403, 'Sudur-Paschim', 'Baitadi', 'Puchaundi Urban Municipality', 'पुचौंडी नगरपालिका'),
(699, 70404, 'Sudur-Paschim', 'Baitadi', 'Surnaya Rural Municipality', 'सुर्नया गाउँपालिका'),
(700, 70405, 'Sudur-Paschim', 'Baitadi', 'Dasharathchand Urban Municipality', 'दशरथचन्द नगरपालिका'),
(701, 70406, 'Sudur-Paschim', 'Baitadi', 'Pancheshwor Rural Municipality', 'पन्चेश्वर गाउँपालिका'),
(702, 70407, 'Sudur-Paschim', 'Baitadi', 'Shivanath Rural Municipality', 'शिवनाथ गाउँपालिका'),
(703, 70408, 'Sudur-Paschim', 'Baitadi', 'Melauli Urban Municipality', 'मेलौली नगरपालिका'),
(704, 70409, 'Sudur-Paschim', 'Baitadi', 'Patan Urban Municipality', 'पाटन नगरपालिका'),
(705, 70410, 'Sudur-Paschim', 'Baitadi', 'Sigas Rural Municipality', 'सिगास गाउँपालिका'),
(706, 70501, 'Sudur-Paschim', 'Dadeldhura', 'Nawadurga Rural Municipality', 'नवदुर्गा गाउँपालिका'),
(707, 70502, 'Sudur-Paschim', 'Dadeldhura', 'Amargadhi Urban Municipality', 'अमरगढी नगरपालिका'),
(708, 70503, 'Sudur-Paschim', 'Dadeldhura', 'Ajayameru Rural Municipality', 'अजयमेरु गाउँपालिका'),
(709, 70504, 'Sudur-Paschim', 'Dadeldhura', 'Bhageshwor Rural Municipality', 'भागेश्वर गाउँपालिका'),
(710, 70505, 'Sudur-Paschim', 'Dadeldhura', 'Parashuram Urban Municipality', 'परशुराम नगरपालिका'),
(711, 70506, 'Sudur-Paschim', 'Dadeldhura', 'Aalital Rural Municipality', 'आलिताल गाउँपालिका'),
(712, 70507, 'Sudur-Paschim', 'Dadeldhura', 'Ganyapdhura Rural Municipality', 'गन्यापधुरा गाउँपालिका'),
(713, 70601, 'Sudur-Paschim', 'Doti', 'Purbichouki Rural Municipality', 'पुर्विचौकी गाउँपालिका'),
(714, 70602, 'Sudur-Paschim', 'Doti', 'Sayal Rural Municipality', 'सायल गाउँपालिका'),
(715, 70603, 'Sudur-Paschim', 'Doti', 'Aadarsha Rural Municipality', 'आदर्श गाउँपालिका'),
(716, 70604, 'Sudur-Paschim', 'Doti', 'Shikhar Urban Municipality', 'शिखर नगरपालिका'),
(717, 70605, 'Sudur-Paschim', 'Doti', 'Dipayal Silgadhi Urban Municipality', 'दिपायल सिलगढी नगरपालिका'),
(718, 70606, 'Sudur-Paschim', 'Doti', 'K.I. Singh Rural Municipality', 'के.आई.सिं. गाउँपालिका'),
(719, 70607, 'Sudur-Paschim', 'Doti', 'Bogatan Phudsil Rural Municipality', 'बोगटान फुड्सिल गाउँपालिका'),
(720, 70608, 'Sudur-Paschim', 'Doti', 'Badi Kedar Rural Municipality', 'बडीकेदार गाउँपालिका'),
(721, 70609, 'Sudur-Paschim', 'Doti', 'Jorayal Rural Municipality', 'जोरायल गाउँपालिका'),
(722, 70701, 'Sudur-Paschim', 'Achham', 'Panchdebal Binayak Urban Municipality', 'पंचदेवल बिनायक नगरपालिका'),
(723, 70702, 'Sudur-Paschim', 'Achham', 'Ramaroshan Rural Municipality', 'रामारोशन गाउँपालिका'),
(724, 70703, 'Sudur-Paschim', 'Achham', 'Mellekh Rural Municipality', 'मेल्लेख गाउँपालिका'),
(725, 70704, 'Sudur-Paschim', 'Achham', 'Sanphebagar Urban Municipality', 'साँफेबगर नगरपालिका'),
(726, 70705, 'Sudur-Paschim', 'Achham', 'Chaurpati Rural Municipality', 'चौरपाटी गाउँपालिका'),
(727, 70706, 'Sudur-Paschim', 'Achham', 'Mangalsen Urban Municipality', 'मंगलसेन नगरपालिका'),
(728, 70707, 'Sudur-Paschim', 'Achham', 'Bannigadhi Jayagadh Rural Municipality', 'बान्नीगढी जयगढ गाउँपालिका'),
(729, 70708, 'Sudur-Paschim', 'Achham', 'Kamal bazar Urban Municipality', 'कमलबजार नगरपालिका'),
(730, 70709, 'Sudur-Paschim', 'Achham', 'Dhakari Rural Municipality', 'ढकारी गाउँपालिका'),
(731, 70710, 'Sudur-Paschim', 'Achham', 'Turmakhand Rural Municipality', 'तुर्माखाँद गाउँपालिका'),
(732, 70801, 'Sudur-Paschim', 'Kailali', 'Mohanyal Rural Municipality', 'मोहन्याल गाउँपालिका'),
(733, 70802, 'Sudur-Paschim', 'Kailali', 'Chure Rural Municipality', 'चुरे गाउँपालिका'),
(734, 70803, 'Sudur-Paschim', 'Kailali', 'Godawari Urban Municipality', 'गोदावरी नगरपालिका'),
(735, 70804, 'Sudur-Paschim', 'Kailali', 'Gauriganga Urban Municipality', 'गौरीगंगा नगरपालिका'),
(736, 70805, 'Sudur-Paschim', 'Kailali', 'Ghodaghodi Urban Municipality', 'घोडाघोडी नगरपालिका'),
(737, 70806, 'Sudur-Paschim', 'Kailali', 'Bardagoriya Rural Municipality', 'बर्दगोरिया गाउँपालिका'),
(738, 70807, 'Sudur-Paschim', 'Kailali', 'Lamki Chuha Urban Municipality', 'लम्कि चुहा नगरपालिका'),
(739, 70808, 'Sudur-Paschim', 'Kailali', 'Janaki Rural Municipality', 'जानकी गाउँपालिका'),
(740, 70809, 'Sudur-Paschim', 'Kailali', 'Joshipur Rural Municipality', 'जोशीपुर गाउँपालिका'),
(741, 70810, 'Sudur-Paschim', 'Kailali', 'Tikapur Urban Municipality', 'टिकापुर नगरपालिका'),
(742, 70811, 'Sudur-Paschim', 'Kailali', 'Bhajani Urban Municipality', 'भजनी नगरपालिका'),
(743, 70812, 'Sudur-Paschim', 'Kailali', 'Kailari Rural Municipality', 'कैलारी गाउँपालिका'),
(744, 70813, 'Sudur-Paschim', 'Kailali', 'Dhangadhi Sub-Metropolitian City', 'धनगढी उपमहानगरपालिका'),
(745, 70901, 'Sudur-Paschim', 'Kanchanpur', 'Krishnapur Urban Municipality', 'कृष्णपुर नगरपालिका'),
(746, 70902, 'Sudur-Paschim', 'Kanchanpur', 'Shuklaphanta Urban Municipality', 'शुक्लाफाँटा नगरपालिका'),
(747, 70903, 'Sudur-Paschim', 'Kanchanpur', 'Bedkot Urban Municipality', 'बेदकोट नगरपालिका'),
(748, 70904, 'Sudur-Paschim', 'Kanchanpur', 'Bhimdatta Urban Municipality', 'भिमदत्त नगरपालिका'),
(749, 70905, 'Sudur-Paschim', 'Kanchanpur', 'Mahakali Urban Municipality', 'महाकाली नगरपालिका'),
(750, 70906, 'Sudur-Paschim', 'Kanchanpur', 'Laljhadi Rural Municipality', 'लालझाडी गाउँपालिका'),
(751, 70907, 'Sudur-Paschim', 'Kanchanpur', 'Punarbas Urban Municipality', 'पुनर्वास नगरपालिका'),
(752, 70908, 'Sudur-Paschim', 'Kanchanpur', 'Belouri Urban Municipality', 'बेलौरी नगरपालिका'),
(753, 70909, 'Sudur-Paschim', 'Kanchanpur', 'Beldandi Rural Municipality', 'बेलडाँडी गाउँपालिका'),
(754, 9999, 'Not Listed', 'Not Listed', 'Not Listed', 'यहाँ उल्लेख गरीएको छैन ');